const {chromium}=require('/Users/jatsmith/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
const userMode=process.env.AGENTPAIR_TEST_ROLE==='user';
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.AGENTPAIR_TEST_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage({viewport:{width:1580,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const stamp=new Date().toISOString();let task={id:'test-console',title:'订单权限评估 · 界面测试',status:'running',round:1,maxRounds:3,results:[],messages:[],events:[]};
 for(let i=0;i<4;i++){const name='Driver '+String.fromCharCode(65+i),id='handoff'+i;task.events.push({at:stamp,round:1,kind:'branch_handoff',role:'Navigator',to:name,message:{id,from:'Navigator',to:name,summary:'验证权限边界 '+i,content:{summary:'请验证订单权限边界，记录完整响应与代码位置。',steps:['检查调用链','运行对照测试']}}},{at:stamp,round:1,kind:'worker_received',role:name,stage:'driver',messageId:id,text:'执行端已接收任务'},{at:stamp,round:1,kind:'tool_started',role:name,stage:'driver',text:'正在执行测试命令',arguments:{command:'pytest tests/test_order_access.py -v'}});}
 task.events.push({at:stamp,round:1,kind:'branch_handoff',role:'Driver A',to:'Driver B',message:{id:'peer1',from:'Driver A',to:'Driver B',summary:'请复核批量接口',content:{summary:'单项接口返回 403。请继续复核批量接口。'}}});
 task.operations={jobs:[{id:'job-b',label:'Job-12',node:'Driver B',round:1,title:'双账户交叉验证',status:'running',objective:'核验批量接口的订单归属权限',progress:{completed:2,total:4},steps:[{title:'下发任务',status:'completed'},{title:'接收上下文',status:'completed'},{title:'执行与取证',status:'running'},{title:'返回结果',status:'pending'}],tools:[{name:'terminal',arguments:{command:'pytest tests/test_order_access.py -v'}}],logs:[{at:stamp,text:'正在验证批量接口',receipt:{arguments:{command:'pytest tests/test_order_access.py -v'}}}]}],acceptance:{passed:3,total:5}};
 task.permissions={canWrite:true};
 const assets=path.join(__dirname,'agentpair/web_assets');
 await page.route('http://console.test/**',async route=>{const u=new URL(route.request().url());let data;if(u.pathname==='/api/balance')data={remainingCNY:2};else if(u.pathname==='/api/session')data={role:userMode?'user':'admin',username:userMode?'alice':'admin',csrf:'test'};else if(u.pathname==='/api/tasks')data={items:[task],budget:{estimatedReservedCNY:0,estimatedLimitCNY:null}};else if(u.pathname==='/api/tasks/test-console')data=task;else if(u.pathname==='/api/resources')data={updatedAt:stamp,activeDrivers:4,tokens:{input:100,output:20,calls:2,missingUsageCalls:0},activeTasks:1,serverEstimatedCNY:.6,generationEstimate:{estimatedReservedCNY:.01},navigator:{cpuCores:2,load1m:0},models:[],leases:[],tasks:[],notes:[]};else if(u.pathname==='/api/credentials')data={items:[]};if(data)return route.fulfill({json:data});const file=path.join(assets,u.pathname==='/'?'workspace.html':u.pathname.slice(1));if(fs.existsSync(file))return route.fulfill({path:file,contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html'});return route.fulfill({status:404,body:'Not found'});});
 await page.goto('http://console.test/');await page.waitForSelector('.tc-node');await page.waitForTimeout(300);
 assert.equal(await page.locator('.tc-node').count(),6);if(userMode){assert((await page.locator('#access-role').innerText()).includes('alice'));assert(await page.locator('#reply-form').isVisible());assert(await page.locator('#logout').isVisible());}
 await page.locator('.tc-node[data-node="Driver B"]').click();await page.locator('[data-tab="messages"]').click();assert((await page.locator('.tc-detail').innerText()).includes('单项接口返回 403'));
 await page.locator('[data-tab="work"]').click();assert((await page.locator('.tc-detail').innerText()).includes('pytest tests/test_order_access.py'));
 assert((await page.locator('.tc-work-heading').innerText()).includes('Job-12'));assert.equal(await page.locator('.tc-jobs progress').getAttribute('value'),'2');
 await page.locator('[data-tab="messages"]').click();await page.screenshot({path:'/private/tmp/agentpair-team-console.png',fullPage:true});
 await page.locator('.tc-work-footer input').uncheck();task=JSON.parse(JSON.stringify(task));task.events.push({at:stamp,round:1,kind:'tool_result',role:'Driver B',stage:'driver',text:'测试已返回',receipt:{tool:'terminal',ok:true,result:{stdout:'4 passed',exitCode:0}}});await page.waitForTimeout(2400);assert((await page.locator('.tc-new').innerText()).includes('新增'));
 await page.locator('#new-task').click();assert(await page.locator('#create').isVisible());assert(await page.locator('#team-console').isHidden());assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS: dynamic nodes, message bodies, tool arguments, polling, follow toggle, publish form; no browser errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
