/** Real controller, synthetic API: request groups, lossless member paging, view defaults and stale delivery. */
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const html = fs.readFileSync('agentpair/web_assets/data_center.html','utf8');
const js = fs.readFileSync('agentpair/web_assets/data_center.js','utf8');
const requestText = '优化 Agent 工作台前端，完成数据中心的布局设计和交互。';
const snapshot = 'frozen-matching-records';
const call = index => ({id:'taste-call-'+index,recordId:'sessionlens:taste-call-'+index,kind:'tool_call',tool:'functions.exec',collector:'sessionlens',application:'codex',deviceId:'mac-one',deviceName:'设计 Mac',timestamp:1791400100-index,capabilities:[{type:'skill',name:'taste-skill',evidence:'read'}],activity:{kind:'skill_read',name:'taste-skill',title:'读取 taste-skill 说明',parameters:[{key:'path',label:'说明文件',value:'/design/taste-skill/SKILL.md'}],request:{text:requestText,recordId:'request-one',association:'candidate',basis:'inferred_source_time'},returnKind:'instructions',returnSummary:'已取得 taste-skill 的操作说明。',calls:[]},summary:{outcome:{status:'exit_zero'}},matchBasis:[{field:'skill',label:'Skill',excerpt:'taste-skill'}]});
const calls = Array.from({length:12},(_,i)=>call(i));
const group = (count=6,id='request-one',association='candidate') => ({id,request:{text:requestText,recordId:id,association,basis:'inferred_source_time'},recordCount:count,firstSeen:calls[count-1].timestamp,lastSeen:calls[0].timestamp,devices:[{id:'mac-one',name:'设计 Mac'}],applications:['codex'],items:calls.slice(0,Math.min(10,count)),hasMore:count>10});
const unknownCall = {...call(0),id:'unknown-call',activity:{...call(0).activity,request:{association:'unknown'}}};
const unknownGroup = {id:'unknown',request:{association:'unknown'},recordCount:1,firstSeen:unknownCall.timestamp,lastSeen:unknownCall.timestamp,devices:[{id:'mac-one',name:'设计 Mac'}],applications:['codex'],items:[unknownCall],hasMore:false};
const result = (groups,extra={}) => ({groups,items:[],total:groups.length,groupTotal:groups.length,recordTotal:groups.reduce((n,g)=>n+g.recordCount,0),requestGroupTotal:groups.filter(g=>g.request.association!=='unknown').length,unassignedRecordTotal:groups.filter(g=>g.request.association==='unknown').reduce((n,g)=>n+g.recordCount,0),page:1,pageSize:20,snapshot,hasMore:false,facets:{devices:[{id:'mac-one',name:'设计 Mac'},{id:'mac-two',name:'测试 Mac'}]},coverage:{retainedRecords:24,searchedRecords:24},...extra});
const response = (data,status=200) => ({ok:status>=200&&status<300,status,json:async()=>data});
const defer = () => {let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const find = (node,test) => node.children.flatMap(child=>[...(test(child)?[child]:[]),...find(child,test)]);
const settle = async () => {for(let i=0;i<8;i++) await new Promise(r=>setImmediate(r));};
class Element {
  constructor(tag='div') {this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.attributes={};this.classes=new Set();this.hidden=false;this.disabled=false;this.value='';this.style={};this._text='';this.dataset={};this.classList={toggle:(key,on)=>on?this.classes.add(key):this.classes.delete(key)};}
  set textContent(value) {this._text=String(value??'');this.children=[];}
  get textContent() {return this._text+this.children.map(child=>child.textContent).join('');}
  set className(value) {this.classes=new Set(value.split(' '));}
  get selectedOptions() {return this.children.filter(child=>child.value===this.value);}
  append(...nodes) {for(const n of nodes) {n.parentElement=this;this.children.push(n);}}
  replaceChildren(...nodes) {this._text='';this.children=[];this.append(...nodes);}
  setAttribute(key,value) {this.attributes[key]=String(value);}
  addEventListener(key,fn) {(this.listeners[key] ||= []).push(fn);}
  async fire(key,extra={}) {for(const fn of this.listeners[key]||[]) fn({target:this,preventDefault(){},stopPropagation(){},...extra});}
  focus() {this.focused=true;} scrollIntoView() {} getClientRects() {return this.hidden?[]:[{}];}
  querySelectorAll() {return find(this,n=>['BUTTON','A','SUMMARY'].includes(n.tagName));}
}
function harness(search='?q=skill%3D%22taste-skill%22') {
  const nodes=new Map(),requests=[],browserListeners={},timers=new Map();let timerId=0,fixture=result([group()]),rawFixture=calls.slice(0,6),memberDeferred=null,memberFail=false;
  for(const match of html.matchAll(/<([a-z][a-z0-9]*)\b[^>]*\bid="([^"]+)"[^>]*>/g)) {const n=new Element(match[1]);n.hidden=/\bhidden\b/.test(match[0]);nodes.set(match[2],n);}
  for(const match of html.matchAll(/<select id="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g)) {const n=nodes.get(match[1]);for(const option of match[2].matchAll(/<option value="([^"]+)"[^>]*>(.*?)<\/option>/g)) {const o=new Element('option');o.value=option[1];o.textContent=option[2];n.append(o);}n.value=n.children[0].value;}
  const $=id=>nodes.get(id),context={document:{getElementById:$,createElement:tag=>new Element(tag),createTextNode:value=>Object.assign(new Element('#text'),{textContent:value}),body:new Element('body'),querySelector:()=>null,addEventListener(){}},location:{origin:'http://localhost',search},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},setTimeout:(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId;},clearTimeout:id=>timers.delete(id),addEventListener:(key,fn)=>browserListeners[key]=fn,AbortController,URL,URLSearchParams,Intl,Date,Number,JSON,Object,String,Set,Map,Array,console,fetch:async(url,options)=>{
    requests.push({url,options}); if(url==='/api/session')return response({});
    if(url.startsWith('/api/data-center/search?')) {
      const p=new URL(url,'http://localhost').searchParams;
      if(p.get('groupId')) {if(memberDeferred)return memberDeferred.promise;if(memberFail)return response({error:'测试加载失败'},503);return response({items:calls.slice(10),group:group(12),total:12,page:Number(p.get('page')),hasMore:false,recordTotal:12,snapshot});}
      return response(p.get('group')==='request'?fixture:{items:rawFixture,total:rawFixture.length,page:Number(p.get('page')),snapshot,hasMore:false});
    }
    if(url.startsWith('/api/data-center/record?')) {const id=new URL(url,'http://localhost').searchParams.get('id'),request=fixture.groups?.flatMap(group=>[group.request,group.request.contextHint].filter(Boolean)).find(request=>request.recordId===id);if(request)return response({item:{id,recordId:'sessionlens:'+id,kind:'user',userInput:request.text,collector:'sessionlens',application:'codex',deviceName:'设计 Mac',timestamp:1791400090,content:{text:request.text},portrait:{userRequest:{userInput:request.text,association:'recorded'},steps:[],neighbors:[]}}});const item=calls.find(call=>call.id===id)||fixture.groups?.flatMap(group=>group.items).find(call=>call.id===id)||rawFixture.find(call=>call.id===id)||unknownCall;return response({item:{...item,arguments:{path:'/design/taste-skill/SKILL.md'},result:{text:'# taste-skill\nFull instructions retained.'},portrait:{userRequest:item.activity?.request||{},steps:[item],neighbors:[]},content:{fixture:id}}});}
    throw Error('Unexpected endpoint '+url);
  }};
  vm.runInNewContext(js,context);
  return {$,requests,context,browserListeners,fixture:value=>fixture=value,rawFixture:value=>rawFixture=value,memberDeferred:value=>memberDeferred=value,memberFail:value=>memberFail=value,submit:async q=>{$('dc-query').value=q;await $('dc-query').fire('input');await $('dc-search-form').fire('submit');await settle();}};
}
const byClass = (node,name) => find(node,n=>n.classes.has(name));
const buttons = node => find(node,n=>n.tagName==='BUTTON');
const searchParams = h => new URL(h.requests.filter(r=>r.url.startsWith('/api/data-center/search?')).at(-1).url,'http://localhost').searchParams;
async function verify() {
  const h=harness();await settle();const card=h.$('dc-results').children[0];
  assert.equal(searchParams(h).get('group'),'request','Skill condition defaults to request groups');
  assert.equal(h.$('dc-results').children.length,1,'six matching calls are represented by one request card');
  assert.equal(h.$('dc-count').textContent,'1 项需求线索 · 6 条匹配记录');
  assert.equal(card.textContent.split(requestText).length-1,1,'request text is presented once');
  assert.match(card.textContent,/前序用户输入.*待确认关联.*设计 Mac.*Codex.*Skill 说明读取 · taste-skill.*6 次.*6 条匹配记录/s);
  await buttons(card).find(b=>b.textContent==='查看用户输入原文 →').fire('click');await settle();assert.match(h.requests.at(-1).url,/id=request-one/,'user-input evidence opens the real anchor record instead of a matching tool call');assert.equal(h.$('dc-detail').hidden,false);assert.equal(h.$('dc-tool-section').hidden,true);assert.match(h.$('dc-content').textContent,/优化 Agent 工作台/);await h.$('dc-close-detail').fire('click');
  assert.equal(byClass(card,'dc-group-members')[0].hidden,true,'calls start collapsed');
  assert.equal(h.$('dc-detail').hidden,true);await card.fire('click');assert.equal(h.$('dc-detail').hidden,true,'request card does not open a record dialog');
  const expand=buttons(card).find(b=>b.textContent==='展开 6 条匹配记录');assert.equal(expand.attributes['aria-expanded'],'false');await expand.fire('click');
  assert.equal(expand.attributes['aria-expanded'],'true');assert.equal(byClass(card,'dc-group-members')[0].hidden,false);assert.equal(byClass(card,'dc-group-member').length,6);
  assert.equal(card.textContent.split(requestText).length-1,1,'expanded matching records do not repeat the request');
  assert.match(byClass(card,'dc-group-member')[0].textContent,/读取 taste-skill 说明.*候选关联.*说明文件.*SKILL.md.*说明返回.*查看原文详情/s);
  await buttons(card).find(b=>b.textContent==='查看原文详情 →').fire('click');await settle();assert.match(h.requests.at(-1).url,/id=taste-call-0/);assert.equal(h.$('dc-detail-title').textContent,'读取 taste-skill 说明');assert.match(h.$('dc-return').textContent,/已取得 taste-skill 的操作说明/);assert.match(h.$('dc-detail-matches').textContent,/Skill.*taste-skill/);await h.$('dc-close-detail').fire('click');
  await h.$('dc-view-record').fire('click');await settle();assert.equal(searchParams(h).has('group'),false);assert.equal(searchParams(h).has('snapshot'),false,'view switch creates a fresh compatible snapshot');assert.equal(h.$('dc-results').children.length,6);assert.equal(h.$('dc-count').textContent,'6 条匹配记录');
  await h.$('dc-view-request').fire('click');await settle();assert.equal(h.$('dc-results').children.length,1);
  h.fixture(result([group(6,'request-one'),group(6,'request-two','recorded'),unknownGroup]));await h.submit('skill="taste-skill"');assert.equal(h.$('dc-results').children.length,3,'different anchors remain distinct even with identical request text');assert.equal(h.$('dc-count').textContent,'2 项需求线索 · 13 条匹配记录 · 1 条归属未确认');assert.match(h.$('dc-results').children[2].textContent,/归属未确认.*独立记录/);
  assert.match(h.$('dc-results').children[1].textContent,/对应用户输入/);assert.match(h.$('dc-results').children[2].textContent,/未找到对应用户输入/);assert.equal(buttons(h.$('dc-results').children[2]).some(button=>button.textContent==='查看用户输入原文 →'),false,'unknown ownership does not invent an anchor evidence entry');
  h.fixture(result([group(12)]));await h.submit('skill="taste-skill"');let large=h.$('dc-results').children[0];assert.equal(byClass(large,'dc-group-member').length,10);assert.equal(byClass(large,'dc-group-members')[0].hidden,true);
  await buttons(large).find(b=>b.textContent==='展开 12 条匹配记录').fire('click');assert.equal(h.$('dc-detail').hidden,true);
  const more=buttons(large).find(b=>b.textContent==='加载更多匹配记录');h.$('dc-query').value='draft query not submitted';await h.$('dc-query').fire('input');h.memberFail(true);await more.fire('click');await settle();
  let p=searchParams(h);assert.equal(p.get('q'),'skill="taste-skill"','member expansion uses frozen submitted query');assert.equal(p.get('snapshot'),snapshot);assert.equal(p.get('groupId'),'request-one');assert.equal(p.get('page'),'2');assert.equal(p.get('pageSize'),'10');assert.match(large.textContent,/测试加载失败/);assert.equal(byClass(large,'dc-group-member').length,10);assert.equal(more.textContent,'重试加载更多');
  h.memberFail(false);await more.fire('click');await settle();assert.equal(byClass(large,'dc-group-member').length,12,'all matching source records remain accessible');assert.equal(more.hidden,true);assert.match(large.textContent,/已展示 12 \/ 12 条匹配记录/);
  await h.submit('skill="taste-skill"');h.$('dc-device').value='mac-one';await h.$('dc-device').fire('change');await settle();large=h.$('dc-results').children[0];await buttons(large).find(b=>b.textContent==='展开 12 条匹配记录').fire('click');await buttons(large).find(b=>b.textContent==='加载更多匹配记录').fire('click');await settle();p=searchParams(h);assert.equal(p.get('device'),'mac-one');assert.equal(p.get('group'),'request');assert.equal(p.get('q'),'skill="taste-skill"','member request keeps all scope filters');
  // Server-side group paging: a group appears on one top-level page, independently from member pages.
  h.fixture(result([group(12)],{total:2,groupTotal:2,requestGroupTotal:2,recordTotal:18,hasMore:true}));await h.submit('skill="taste-skill"');h.fixture(result([group(6,'request-two','recorded')],{total:2,groupTotal:2,requestGroupTotal:2,recordTotal:18,page:2}));await h.$('dc-next').fire('click');await settle();assert.equal(searchParams(h).get('snapshot'),snapshot);assert.match(h.$('dc-page-position').textContent,/第 2 页 · 本页 1 个分组/);assert.equal(h.$('dc-count').textContent,'2 项需求线索 · 18 条匹配记录');assert.equal(byClass(h.$('dc-results'),'dc-group-member').length,6);
  // A late member request cannot repopulate a new query or a different result view.
  h.fixture(result([group(12)]));await h.submit('skill="taste-skill"');large=h.$('dc-results').children[0];await buttons(large).find(b=>b.textContent==='展开 12 条匹配记录').fire('click');const delayed=defer();h.memberDeferred(delayed);await buttons(large).find(b=>b.textContent==='加载更多匹配记录').fire('click');await settle();await h.$('dc-view-record').fire('click');await settle();delayed.resolve(response({items:calls.slice(10),page:2,hasMore:false}));await settle();assert.equal(h.$('dc-results').children.length,6);assert.equal(byClass(h.$('dc-results'),'dc-group-member').length,0);assert.equal(byClass(large,'dc-group-member').length,10,'late stale data does not alter detached request card');h.memberDeferred(null);
  for(const q of ['tool="Bash"','192.0.2.1','taste-skill']) {await h.submit(q);assert.equal(searchParams(h).has('group'),false,'generic searches retain original records by default');}
  await h.submit('tool="functions.exec" && mcp="tinyfish"');assert.equal(searchParams(h).get('group'),'request','MCP condition defaults to groups');
  // Generic tools use the user input as the primary result, without pretending that a matched excerpt is a return.
  const execItems=Array.from({length:10},(_,index)=>({...call(index),id:'exec-'+index,tool:'exec',function:'functions.exec',capabilities:[],activity:null,request:{text:'查天气',recordId:'weather-input',association:'recorded'},summary:{action:'调用工具 · exec',parameters:[{key:'code',label:'执行代码',value:'await tools.exec_command({cmd:"curl https://wttr.in/Shanghai"})'}],resultPreview:index===0?'上海：23℃，附近局部降雨':'',outcome:{}},excerpt:'EXEC_QUERY_MATCH_IS_NOT_A_TOOL_RETURN'}));
  const execGroup={...group(12,'weather-input','recorded'),request:{text:'查天气',recordId:'weather-input',association:'recorded'},items:execItems,toolCallCounts:[{name:'exec',count:11}]};h.fixture(result([execGroup]));await h.submit('tool="exec"');await h.$('dc-view-request').fire('click');await settle();const execCard=h.$('dc-results').children[0];assert.equal(execCard.children[0].children[0].children[1].textContent,'查天气','a short but recorded user input is not discarded by presentation filtering');assert.match(execCard.textContent,/对应用户输入.*查天气.*设计 Mac.*Codex.*工具 · exec.*11 次调用.*12 条匹配记录/s);assert.equal(byClass(execCard,'dc-group-member').length,10,'card count uses full group tool-call counts rather than its 10-row preview');assert.match(byClass(execCard,'dc-group-member')[0].textContent,/工具exec.*函数：functions.exec.*执行代码.*wttr.in.*返回摘要上海：23℃/s);assert.match(byClass(execCard,'dc-group-member')[1].textContent,/未找到可对应的工具返回/);assert.doesNotMatch(execCard.textContent,/EXEC_QUERY_MATCH_IS_NOT_A_TOOL_RETURN/);await buttons(execCard).find(b=>b.textContent==='查看用户输入原文 →').fire('click');await settle();assert.match(h.requests.at(-1).url,/id=weather-input/);await h.$('dc-close-detail').fire('click');
  h.rawFixture(execItems.slice(0,2));await h.$('dc-view-record').fire('click');await settle();assert.equal(h.$('dc-results').children.length,2);assert.match(h.$('dc-results').children[0].textContent,/上报机器：设计 Mac.*Codex.*用户输入原记录关联查天气/s,'raw generic tool cards also retain their user input');await buttons(h.$('dc-results').children[0]).find(button=>button.textContent==='查看完整信息 →').fire('click');await settle();assert.match(h.$('dc-task-context').textContent,/查天气.*用户输入有原记录关联/s,'generic tool details use the explicit backend request anchor');await h.$('dc-close-detail').fire('click');
  // Passthrough/root-turn evidence retains the actual continuation rather than inventing a complete task.
  const hintText='请检查原始需求关联以及用户输入的展示。'+ '保留前序线索。'.repeat(45)+'HINT_TAIL_NOT_VISIBLE',rootRequest={text:'。',recordId:'root-input',association:'recorded',basis:'recorded_root_turn_parent_session',inputKind:'continuation',contextHint:{text:hintText,recordId:'prior-input',association:'candidate'}};
  const continuation={...execItems[0],id:'root-exec',request:rootRequest},blank={...execItems[1],id:'blank-exec',request:{association:'unknown',reason:'已记录主轮次，但未找到对应用户输入'}},rootGroup={...group(1,'root-group','recorded'),request:rootRequest,items:[continuation],toolCallCounts:[{name:'exec',count:1}]};h.rawFixture([continuation,blank]);h.fixture(result([rootGroup]));await h.submit('tool="exec"');const rootCard=h.$('dc-results').children[0];assert.match(rootCard.textContent,/本轮用户输入（续接）主会话原文关联。.*不代表完整需求.*前序需求线索候选线索.*尚未确认与本轮属于同一任务/s);assert.doesNotMatch(rootCard.textContent,/HINT_TAIL_NOT_VISIBLE|人员身份已确认|已确认同一任务/);assert.match(h.$('dc-results').children[1].textContent,/用户输入未关联.*已记录主轮次，但未找到对应用户输入/s,'missing-input diagnostics remain visible on compact record cards');await buttons(rootCard).find(button=>button.textContent==='查看完整信息 →').fire('click');await settle();assert.match(h.$('dc-task-context').textContent,/主会话原文关联。.*前序需求线索.*用户输入来自主会话的原始记录/s);await h.$('dc-close-detail').fire('click');await h.$('dc-view-request').fire('click');await settle();const groupedRoot=h.$('dc-results').children[0];assert.equal(groupedRoot.children[0].children[0].children[1].textContent,'。','punctuation continuation remains the actual source input');assert.match(groupedRoot.textContent,/本轮用户输入（续接）.*主会话原文关联.*前序需求线索候选线索/s);await buttons(groupedRoot).find(button=>button.textContent==='查看前序输入原文 →').fire('click');await settle();assert.match(h.requests.at(-1).url,/id=prior-input/);assert.match(h.$('dc-content').textContent,/请检查原始需求关联/);await h.$('dc-close-detail').fire('click');
  rootRequest.text='做';await h.submit('tool="exec"');await h.$('dc-view-request').fire('click');await settle();assert.equal(h.$('dc-results').children[0].children[0].children[0].children[1].textContent,'做','one-character continuation is not filtered or replaced by a preceding request');
  await h.submit('');h.$('dc-object').value='skill';await h.$('dc-object').fire('change');await settle();assert.equal(searchParams(h).get('group'),'request','Skill object defaults to groups even with empty query');
  assert.ok(h.requests.every(r=>r.options.method==='GET'));assert.doesNotMatch(js,/innerHTML\s*=/);h.browserListeners.pagehide();
  console.log('PASS: User-input-first request cards, real anchor evidence navigation, generic exec tools/arguments/returns and full-group call counts, candidate and unknown certainty, distinct anchors, member paging/retry, frozen scope/snapshot and stale cancellation. Synthetic DOM/API only.');
}
if(process.argv.includes('--serve')) {
  const http=require('node:http'),path=require('node:path'),port=Number(process.argv[process.argv.indexOf('--serve')+1]||18968),assets=path.resolve('agentpair/web_assets');
  http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');res.setHeader('Cache-Control','no-store');if(u.pathname==='/api/session'){res.setHeader('Content-Type','application/json');return res.end('{}');}if(u.pathname.startsWith('/api/data-center/')){res.setHeader('Content-Type','application/json');const data=u.pathname.endsWith('/record')?{item:{...calls[0],arguments:{path:'/design/taste-skill/SKILL.md'},result:{text:'Full retained instructions.'},content:{synthetic:true}}}:u.searchParams.get('groupId')?{items:calls.slice(10),total:12,page:2,hasMore:false}:u.searchParams.get('group')==='request'?result([group(u.searchParams.get('q')?.includes('twelve')?12:6)]):{items:calls.slice(0,6),total:6,page:1};return res.end(JSON.stringify(data));}const file=u.pathname==='/'||u.pathname==='/model-data'?'data_center.html':path.basename(u.pathname);try{res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html');res.end(fs.readFileSync(path.join(assets,file)));}catch(_){res.statusCode=404;res.end('Not found');}}).listen(port,'127.0.0.1',()=>console.log('Synthetic request groups preview http://127.0.0.1:'+port+'/model-data?q=skill%3D%22taste-skill%22'));
} else verify().catch(e=>{console.error(e);process.exitCode=1;});
