/** Actual data-center controller; synthetic read-only execution contracts, no browser/model calls. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('agentpair/web_assets/data_center.html','utf8'),js=fs.readFileSync('agentpair/web_assets/data_center.js','utf8');
const find=(node,predicate)=>node.children.flatMap(child=>[...(predicate(child)?[child]:[]),...find(child,predicate)]);
const visible=node=>node.hidden?'':node.tagName==='DETAILS'&&!node.open?node.children.find(child=>child.tagName==='SUMMARY')?.textContent||'':node._text+node.children.map(visible).join('');
const byClass=(node,name)=>find(node,child=>child.classes.has(name));
const returned=(extra={})=>({id:'return-one',association:'outer_single_operation',basis:'single literal operation',status:'exit_zero',statusLabel:'退出码 0',exitCode:0,contentType:'code',summary:'返回文件中的代码内容',preview:'DELETE FROM accounts;\nSELECT * FROM users;',content:'DELETE FROM accounts;\nSELECT * FROM users;',technical:{chunkId:'hidden-chunk-marker',index:19},...extra});
const operation=(index,extra={})=>({id:'operation-'+index,function:'tools.exec_command',arguments:{cmd:'sed -n "1,20p" /repo/analysis.sql',workdir:'/repo'},command:'sed -n "1,20p" /repo/analysis.sql',cwd:'/repo',action:'读取文件',objectSummary:'analysis.sql · 第 1–20 行',targets:[{kind:'file',value:'/repo/analysis.sql',label:'读取文件'}],sourceOffset:11,sourceEnd:99,sourceBasis:'static_outer_code',return:returned(),...extra});
const execution=(extra={})=>({outer:{tool:'exec',callId:'outer-call-marker',status:'completed',statusLabel:'外层脚本已完成',durationSeconds:.8},operations:[operation(1)],returns:[returned()],coverage:{operationsIdentified:1,sourceTruncated:false,returnTruncated:false,unpairedReturns:0,limitations:['Returned code is content, not proof of execution']},...extra});
const common={kind:'tool_call',kindLabel:'工具调用',collector:'sessionlens',application:'codex',deviceName:'研发 Mac',deviceId:'mac-one',ownerAccount:'qa-user',timestamp:1791400100,tool:'exec',function:'functions.exec',request:{text:'检查仓库里的数据分析脚本',recordId:'request-one',association:'recorded'},summary:{action:'调用工具 · exec',resultPreview:'OLD_WRAPPER_RESULT_SHOULD_NOT_REPEAT',parameters:[{key:'code',value:'RAW_OUTER_CODE_MARKER'}],outcome:{status:'exit_zero'}}};
const single={...common,id:'single',execution:execution()};
const unpairedOperations=Array.from({length:5},(_,index)=>operation(index+1,{action:index?'读取文件':'访问网址',objectSummary:index?'config-'+index+'.json':'https://wttr.in/Shanghai',targets:[{kind:index?'file':'url',value:index?'/repo/config-'+index+'.json':'https://wttr.in/Shanghai',label:index?'读取文件':'访问地址'}],return:{association:'unconfirmed',status:'unknown',statusLabel:'尚未逐项配对'}}));
const unpairedReturns=Array.from({length:4},(_,index)=>returned({id:'unpaired-'+index,association:'unassigned',contentType:'json',summary:'返回天气字段：城市 Shanghai、温度 23℃',preview:JSON.stringify({city:'Shanghai',temperature:'23℃',i:index,chunk_id:'hidden-json-chunk-marker'}),content:{city:'Shanghai',temperature:'23℃',nested:{humidity:'82%',i:index},i:index,chunk_id:'hidden-json-chunk-marker'}}));
const multiple={...common,id:'multiple',request:{...common.request,text:'查上海天气并检查配置'},execution:execution({operations:unpairedOperations,returns:unpairedReturns,coverage:{unpairedReturns:4,operationsIdentified:5,limitations:['Do not pair by order']}})};
const skill={...common,id:'skill',execution:execution({operations:[operation(1,{objectSummary:'SKILL.md',targets:[{kind:'file',value:'/design/taste-skill/SKILL.md',label:'读取文件'}],arguments:{cmd:'cat /design/taste-skill/SKILL.md'}})]}),capabilities:[{type:'skill',name:'taste-skill',evidence:'read'}],activity:{kind:'skill_read',name:'taste-skill',title:'读取 taste-skill 说明',parameters:[{key:'path',label:'说明文件',value:'/design/taste-skill/SKILL.md'}],request:common.request,returnKind:'instructions',returnSummary:'已取得 taste-skill 的操作说明。',calls:[]}};
const fallback={...common,id:'fallback',tool:'Bash',execution:null,summary:{action:'执行本机命令',parameters:[{key:'cmd',value:'echo fallback'}],resultPreview:'legacy-tool-result',outcome:{status:'exit_zero'}}};
const missing={...common,id:'missing',execution:execution({outer:{tool:'exec',status:'running',statusLabel:'外层脚本仍在运行'},operations:[operation(1,{action:'调用 tools.exec_command（参数为动态表达式）',objectSummary:'',targets:[],arguments:null,command:null,return:{association:'unconfirmed',status:'unknown'}})],returns:[]})};
const deferred={...common,id:'deferred',execution:{outer:{tool:'exec',status:'unknown',statusLabel:'尚未解析执行内容'},operations:[],returns:[],coverage:{incomplete:true,sourceTruncated:true,limitations:['page budget']}}};
const nonText={...common,id:'nontext',execution:execution({operations:[],returns:[returned({association:'unassigned',contentType:'non_text',summary:'返回非文本内容 · image',preview:'',content:{type:'image',data:'BASE64_PAYLOAD_SHOULD_BE_FOLDED'}})],outer:{tool:'exec',status:'completed',nonTextBlocks:1},coverage:{nonTextBlocks:1}})};
const partial={...common,id:'partial',execution:execution({operations:[operation(1,{return:{association:'unconfirmed',status:'unknown'}})],returns:[],coverage:{incomplete:true,returnProjectionUnavailable:true}})};
const rows=[single,multiple,skill,fallback,missing,deferred,nonText,partial],details=Object.fromEntries(rows.map(item=>[item.id,{...item,arguments:{code:'RAW_OUTER_CODE_MARKER'},result:{chunk_id:'hidden-chunk-marker',i:19,output:'raw-wrapper-content'},content:{raw:'preserved'},raw:{output:'raw-wrapper-content'},sourceEvidence:{retained:true},portrait:{userRequest:item.request,steps:[],neighbors:[]}}]));
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.attributes={};this.dataset={};this.classes=new Set();this.hidden=false;this.disabled=false;this.value='';this.style={};this._text='';this.classList={toggle:(key,on)=>on?this.classes.add(key):this.classes.delete(key)};}set textContent(value){this._text=String(value??'');this.children=[];}get textContent(){return this._text+this.children.map(child=>child.textContent).join('');}set className(value){this.classes=new Set(value.split(' '));}get selectedOptions(){return this.children.filter(child=>child.value===this.value);}append(...nodes){for(const n of nodes){n.parentElement=this;this.children.push(n);}}replaceChildren(...nodes){this._text='';this.children=[];this.append(...nodes);}setAttribute(key,value){this.attributes[key]=String(value);}addEventListener(key,fn){(this.listeners[key]||=[]).push(fn);}async fire(key,extra={}){for(const fn of this.listeners[key]||[])fn({target:this,preventDefault(){},stopPropagation(){},...extra});}focus(){}scrollIntoView(){}getClientRects(){return this.hidden?[]:[{}];}querySelectorAll(){return find(this,node=>['BUTTON','A','SUMMARY'].includes(node.tagName));}}
const settle=async()=>{for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve));};
function harness(search='?q=tool%3D%22exec%22'){const nodes=new Map(),requests=[],timers=new Map();let timerId=0;for(const match of html.matchAll(/<([a-z][a-z0-9]*)\b[^>]*\bid="([^"]+)"[^>]*>/g)){const node=new Element(match[1]);node.hidden=/\bhidden\b/.test(match[0]);nodes.set(match[2],node);}for(const match of html.matchAll(/<select id="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g)){const node=nodes.get(match[1]);for(const option of match[2].matchAll(/<option value="([^"]+)"[^>]*>(.*?)<\/option>/g)){const child=new Element('option');child.value=option[1];child.textContent=option[2];node.append(child);}node.value=node.children[0].value;}
const $=id=>nodes.get(id),context={document:{getElementById:$,createElement:tag=>new Element(tag),createTextNode:value=>Object.assign(new Element('#text'),{textContent:value}),body:new Element('body'),querySelector:()=>null,addEventListener(){}},location:{origin:'http://localhost',search},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},setTimeout:(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId;},clearTimeout:id=>timers.delete(id),addEventListener(){},AbortController,URL,URLSearchParams,Intl,Date,Number,JSON,Object,String,Set,Map,Array,console,fetch:async(url,options)=>{requests.push({url,options});let data;if(url==='/api/session')data={};else if(url.startsWith('/api/data-center/search?')){const p=new URL(url,'http://localhost').searchParams;data=p.get('group')==='request'?{groups:[{id:'group-one',request:common.request,recordCount:5,toolCallCounts:[{name:'exec',count:5}],firstSeen:1791400100,lastSeen:1791400101,devices:[{id:'mac-one',name:'研发 Mac'}],applications:['codex'],items:rows,hasMore:false}],items:[],total:1,groupTotal:1,requestGroupTotal:1,recordTotal:5,page:1}:{items:rows,total:5,page:1};}else if(url.startsWith('/api/data-center/record?'))data={item:details[new URL(url,'http://localhost').searchParams.get('id')]};else throw Error('unexpected '+url);return{ok:true,status:200,json:async()=>data};}};vm.runInNewContext(js,context);return{$,requests,open:async index=>{await $('dc-results').children[index].fire('click');await settle();}};}
(async()=>{const h=harness();await settle();const cards=h.$('dc-results').children;assert.equal(cards.length,8);const first=cards[0];assert.match(visible(first),/研发 Mac.*Codex.*用户输入原记录关联检查仓库里的数据分析脚本.*读取文件.*analysis.sql.*返回的代码.*退出码 0.*返回文件中的代码内容/s);assert.doesNotMatch(visible(first),/DELETE FROM|SELECT \*|RAW_OUTER_CODE_MARKER|OLD_WRAPPER|hidden-chunk-marker|outer-call-marker/);assert.equal(byClass(first,'dc-execution-return').length,1,'one single-operation return is shown once');assert.equal(byClass(first,'dc-result-outcome').length,0,'old wrapper result is not repeated');assert.ok(find(first,node=>node.tagName==='DETAILS').every(node=>!node.open),'parameters, code and technical wrappers begin folded');
const content=byClass(first,'dc-execution-content')[0];content.open=true;assert.match(visible(content),/DELETE FROM accounts/);content.open=false;assert.match(visible(first),/是否实际运行需对应执行记录/);await h.open(0);assert.equal(h.$('dc-execution-detail').hidden,false);assert.equal(h.$('dc-tool-grid').hidden,true);assert.equal(h.$('dc-tool-facts').hidden,true);assert.match(visible(h.$('dc-execution-detail')),/读取文件.*analysis.sql.*返回文件中的代码内容/s);assert.doesNotMatch(visible(h.$('dc-execution-detail')),/DELETE FROM|hidden-chunk-marker/);assert.match(h.$('dc-content').textContent,/preserved/);assert.match(h.$('dc-raw').textContent,/raw-wrapper-content/);
const multi=cards[1],ops=byClass(multi,'dc-execution-operation'),moreOps=byClass(multi,'dc-execution-more-operations')[0],moreReturns=byClass(multi,'dc-execution-more-returns')[0];assert.equal(ops.length,5);assert.match(visible(multi),/访问网址.*wttr.in\/Shanghai.*外层返回 · 未逐项配对.*城市 Shanghai、温度 23℃/s);assert.equal(moreOps.children.filter(node=>node.classes.has('dc-execution-operation')).length,2);assert.equal(moreReturns.children.filter(node=>node.classes.has('dc-execution-return')).length,2);assert.match(visible(multi),/另 2 项已识别操作.*另 2 份外层返回/s);assert.ok(ops.every(node=>byClass(node,'dc-execution-return').length===0),'multiple inner operations never receive copied outer results');assert.doesNotMatch(visible(multi),/hidden-json-chunk-marker|chunk_id|hidden-chunk-marker/);const jsonContent=byClass(multi,'dc-execution-content')[0];jsonContent.open=true;assert.match(visible(jsonContent),/cityShanghai.*temperature23℃.*nested.*humidity82%/s);assert.doesNotMatch(visible(jsonContent),/hidden-json-chunk-marker/);assert.equal(byClass(jsonContent,'dc-execution-fields').length>=2,true,'JSON objects render as nested labelled fields');jsonContent.open=false;
await h.open(1);assert.equal(byClass(h.$('dc-execution-detail'),'dc-execution-more-operations').length,0,'detail exposes all identified operations');assert.equal(byClass(h.$('dc-execution-detail'),'dc-execution-more-returns').length,0);assert.equal(byClass(h.$('dc-execution-detail'),'dc-execution-operation').length,5);
assert.match(visible(cards[2]),/读取 taste-skill 说明.*已取得 taste-skill 的操作说明.*内部操作.*读取文件.*SKILL.md/s);assert.doesNotMatch(visible(cards[2]),/返回的代码|DELETE FROM|已交付|已运行/,'Skill documentation remains documentation rather than a task artifact');await h.open(2);assert.equal(h.$('dc-execution-detail').hidden,true);assert.equal(h.$('dc-tool-grid').hidden,false);assert.match(h.$('dc-arguments').textContent,/内部操作.*cat \/design\/taste-skill\/SKILL.md/s);assert.match(visible(h.$('dc-return')),/已取得 taste-skill 的操作说明/);
await h.open(3);assert.equal(h.$('dc-execution-detail').hidden,true);assert.equal(h.$('dc-tool-grid').hidden,false);assert.match(visible(cards[3]),/legacy-tool-result.*echo fallback/s,'records without execution keep the old readable rendering');assert.match(visible(cards[4]),/参数为动态表达式.*脚本仍在运行，等待后续返回/s);assert.doesNotMatch(visible(cards[4]),/退出码 0|已完成任务|未找到可对应的外层返回/);assert.match(visible(cards[4]),/外层脚本仍在运行/);assert.match(visible(cards[0]),/外层脚本已完成.*耗时 0.8 秒/s);assert.match(visible(cards[6]),/返回非文本内容 · image.*另有 1 份非文本返回，原文可查看/s);assert.doesNotMatch(visible(cards[6]),/BASE64_PAYLOAD_SHOULD_BE_FOLDED|未找到可对应的外层返回/);assert.match(visible(cards[5]),/当前页尚未解析执行内容，可查看完整信息/);assert.doesNotMatch(visible(cards[5]),/RAW_OUTER_CODE_MARKER|OLD_WRAPPER|未找到可对应的外层返回/,'parse-budget deferral stays readable without pretending that retained return data is missing');
assert.match(visible(cards[7]),/已有外层返回，本页未展开；记录详情可查看/);assert.doesNotMatch(visible(cards[7]),/未找到可对应的外层返回|未采集内部调用的独立返回/);
await h.$('dc-close-detail').fire('click');await h.$('dc-view-request').fire('click');await settle();const grouped=h.$('dc-results').children[0];assert.match(visible(grouped),/对应用户输入检查仓库里的数据分析脚本.*研发 Mac.*Codex/);const members=byClass(grouped,'dc-group-members')[0];members.hidden=false;assert.equal(byClass(members,'dc-execution').length,7);assert.match(visible(members),/读取文件.*analysis.sql.*返回文件中的代码内容.*外层返回 · 未逐项配对/s);assert.doesNotMatch(visible(members),/OLD_WRAPPER_RESULT_SHOULD_NOT_REPEAT/);assert.ok(h.requests.every(request=>request.options.method==='GET'));assert.doesNotMatch(js,/innerHTML\s*=/);assert.match(html,/data_center\.js\?v=[a-z0-9-]+/);console.log('PASS: Readable exec operations/objects/results across raw cards, grouped members and details; compact limits; code and parameters folded; JSON fields readable; multi-call returns unpaired; Skill documentation preserved; old rendering fallback and raw evidence retained. Synthetic DOM/API only.');})().catch(error=>{console.error(error);process.exitCode=1;});
