/** Regression of the actual Data Center controller with synthetic DOM/API; no model/network. */
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const html = fs.readFileSync('agentpair/web_assets/data_center.html','utf8');
const js = fs.readFileSync('agentpair/web_assets/data_center.js','utf8');
let active;
class Element {
  constructor(tag='div') {this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.attributes={};this.classes=new Set();this.hidden=false;this.disabled=false;this.checked=false;this.value='';this.style={};this._text='';this.dataset={};this.classList={toggle:(key,on)=>on?this.classes.add(key):this.classes.delete(key)};}
  set textContent(x) {this._text=String(x??'');this.children=[];}
  get textContent() {return this._text+this.children.map(n=>n.textContent).join('');}
  set className(x) {this.classes=new Set(x.split(' '));}
  get selectedOptions() {return this.children.filter(n=>n.value===this.value);}
  append(...nodes) {for (const n of nodes) {n.parentElement=this;this.children.push(n);}}
  replaceChildren(...nodes) {this.children=[];this._text='';this.append(...nodes);}
  setAttribute(k,v) {this.attributes[k]=String(v);}
  addEventListener(k,f) {(this.listeners[k] ||= []).push(f);}
  async fire(k,extra={}) {const e={preventDefault(){},stopPropagation(){},target:this,...extra};for (const f of this.listeners[k] || []) f(e);}
  focus() {active=this;}
  scrollIntoView() {this.scrolled=true;}
  getClientRects() {return this.hidden?[]:[{}];}
  querySelectorAll() {return find(this,n=>['BUTTON','A','SUMMARY'].includes(n.tagName));}
}
const find=(node,predicate)=>node.children.flatMap(n=>[...(predicate(n)?[n]:[]),...find(n,predicate)]);
const nodes=new Map();
for (const match of html.matchAll(/<([a-z][a-z0-9]*)\b[^>]*\bid="([^"]+)"[^>]*>/g)) {const node=new Element(match[1]);node.hidden=/\bhidden\b/.test(match[0]);node.disabled=/\bdisabled\b/.test(match[0]);node.required=/\brequired\b/.test(match[0]);nodes.set(match[2],node);}
for (const match of html.matchAll(/<select id="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g)) {const node=nodes.get(match[1]);for(const option of match[2].matchAll(/<option value="([^"]+)"[^>]*>(.*?)<\/option>/g)){const el=new Element('option');el.value=option[1];el.textContent=option[2];node.append(el);}node.value=node.children[0].value;}
const $=id=>nodes.get(id), body=new Element('body'), documentListeners={}, browserListeners={}, memory=new Map(), requests=[];
const originalArgument='full original password ending 1234 and nested argument';
const common={collector:'sessionlens',application:'workbuddy',ownerAccount:'admin',operator:'未确认',deviceId:'device-one',deviceName:'研发电脑',sessionId:'one-session-two-goals',timestamp:1791354000,receivedAt:null,confirmation:'recorded',addressBasis:'not_collected'};
const weather={...common,id:'dc_weather',recordId:'sessionlens:weather',kind:'tool_call',kindLabel:'工具调用',title:'工具调用 · Bash · curl',tool:'Bash',function:null,command:'curl -fsSL https://weather.example.test/Shanghai?format=json',destination:'https://weather.example.test/Shanghai?format=json',addressBasis:'tool_argument_target',excerpt:'调用 curl 查询天气服务',matchBasis:[{field:'arguments',label:'工具参数',excerpt:'curl -fsSL https://weather.example.test/Shanghai?format=json'}],rawUrl:'/api/data-center/raw?id=dc_weather'};
const video={...common,id:'dc_video',recordId:'sessionlens:video',kind:'tool_call',title:'工具调用 · videoGen',tool:'MCP',function:'videoGen',command:null,destination:null,excerpt:'生成视频的工具调用',matchBasis:[{field:'arguments',label:'工具参数',excerpt:'生成五秒 SSH 动画'}]};
const mention={...common,id:'dc_mention',recordId:'sessionlens:mention',kind:'user',kindLabel:'用户输入',title:'用户输入 · 地址提及',destination:'https://mentioned.example.test',addressBasis:'text_mention',excerpt:'<script>window.leak=true</script>',matchBasis:[{field:'user',label:'用户输入',excerpt:'正文提到 https://mentioned.example.test'}]};
const addressRecord={...weather,destination:'https://192.0.2.10/',command:'curl https://192.0.2.10/ # investigate 192.0.2.1',matchBasis:[{field:'arguments',label:'工具参数中的注释',addressBasis:'text_mention',matchedAddress:'192.0.2.1',excerpt:'curl https://192.0.2.10/ # investigate 192.0.2.1'}]};
const contextRecord={...common,id:'dc_context',recordId:'applens:context',collector:'applens',kind:'context',title:'装配上下文记录',excerpt:'上下文包含原始凭据片段'};
const details={
 dc_weather:{...weather,arguments:{command:weather.command,nested:{untouched:originalArgument}},result:{status:'ok',city:'Shanghai',temperature:25,nested:{units:'C'}},content:{arguments:{command:weather.command}},raw:{callId:'call-weather',original:originalArgument},related:[{...weather,id:'dc_weather_return',recordId:'sessionlens:return',kind:'tool_result',title:'工具返回 · 天气服务',excerpt:'上海 25°C'}],relations:[{from:'dc_weather',to:'dc_weather_return',relation:'tool_call_result',basis:'唯一调用标识'}],taskContext:{userInput:'查一下上海天气',association:'candidate',basis:'前序用户输入候选，未确定任务边界'},gaps:['未采集到工具返回进入下一份模型输入的直接关系'],sourceEvidence:{layer:'应用日志',retained:true}},
 dc_video:{...video,arguments:{prompt:'五秒 SSH 动画',seconds:5},result:null,raw:{callId:'duplicate-id'},content:'videoGen 参数',related:[],relations:[],taskContext:{association:'unavailable'},gaps:['调用标识重复，未将最近一条返回当成对应返回'],sourceEvidence:{layer:'应用日志'}},
 dc_mention:{...mention,content:mention.excerpt,raw:{text:mention.excerpt},related:[],relations:[],taskContext:{association:'unavailable'},gaps:[],sourceEvidence:null},
 dc_context:{...contextRecord,content:{background:originalArgument},raw:{body:originalArgument},contextItems:[{name:'系统背景',source:'装配上下文',text:originalArgument}],related:[],relations:[],taskContext:{association:'unavailable'},gaps:['HTTP 请求头和响应未采集'],sourceEvidence:{layer:'本地装配上下文'}}
};
const chainUser={...common,id:'dc_user',kind:'user',title:'用户输入 · 查询天气'};
const chainThought={...common,id:'dc_thought',kind:'reasoning',title:'已记录思路 · 选择天气服务'};
details.dc_weather.matchBasis=[];
details.dc_weather.related.push(chainThought,chainUser);
details.dc_weather.taskContext.basis='recorded_source_parent';
details.dc_weather.relations[0].basis='recorded_unique_call_id';
details.dc_weather.relations.push({from:'dc_thought',to:'dc_weather',relation:'source_parent',basis:'recorded_unique_parent_id'},{from:'dc_user',to:'dc_thought',relation:'source_parent',basis:'recorded_unique_parent_id'});
// Additive portrait contract. These are synthetic captures, not hardcoded product examples.
const weatherPortrait={...weather,id:'dc_weather_portrait',summary:{action:'请求天气服务',target:'https://weather.example.test/Shanghai?format=json',parameters:[{key:'command',label:'执行命令',value:'curl weather.example.test/Shanghai'}],resultPreview:'上海：23℃ · 体感24℃ · 湿度82% · Patchy rain nearby',outcome:{status:'ok',label:'返回码为0',sourceTruncated:true,facts:[{label:'气温',value:'23℃'},{label:'体感温度',value:'24℃'},{label:'湿度',value:'82%'},{label:'天气',value:'Patchy rain nearby'}]}},sourceDeviceId:'physical-device-one'};
const portraitReply={...common,id:'dc_portrait_reply',kind:'reply',title:'Agent 回复',presentation:{bodyText:'上海当前23℃，附近有局部降雨。'},summary:{action:'Agent 回复'}};
const portraitReasoning={...common,id:'dc_portrait_reasoning',kind:'reasoning',title:'已记录思路',presentation:{bodyText:'查询上海的天气 JSON，然后核对当前温度与湿度。'}};
details.dc_weather_portrait={...details.dc_weather,...weatherPortrait,presentation:{parameters:[{key:'command',label:'执行命令',value:weather.command}],result:{status:'ok',label:'工具返回码为0',exitCode:0,facts:[{label:'气温',value:'23℃'},{label:'体感温度',value:'24℃'},{label:'湿度',value:'82%'},{label:'天气',value:'Patchy rain nearby'}],parsed:{current_condition:[{temp_C:'23',FeelsLikeC:'24',humidity:'82'}],weather:[{date:'2026-09-11',mintempC:'22',maxtempC:'29',hourly:[{weatherDesc:[{value:'Patchy rain nearby'}]}]}]}}},portrait:{userRequest:{userInput:'查一下上海天气',association:'recorded',basis:'recorded_source_parent'},steps:[{...chainUser,association:'recorded',userInput:'查一下上海天气',presentation:{bodyText:'<system-reminder>craft_mode</system-reminder>查一下上海天气'}},{...portraitReasoning,association:'recorded',relationBasis:'recorded_source_relation'},weatherPortrait,{...portraitReply,association:'candidate'}],neighbors:[{...mention,id:'dc_neighbor',association:'same_session_neighbor'}],coverage:{sourceSessionsAreTasks:false,contentLimitPerRecord:60000,truncatedRecords:1}}};
const videoPortrait={...video,id:'dc_video_portrait',tool:'VideoGen',executor:'DeferExecuteTool',function:'DeferExecuteTool',summary:{action:'生成SSH动画',promptPreview:'将SSH握手过程制作成动画',parameters:[{key:'resolution',label:'分辨率',value:'1080P'},{key:'enable_audio',label:'生成音频',value:false}],outcome:{status:'completed',label:'工具返回完成',outputs:[{label:'SSH动画',path:'/workspace/ssh-handshake.mp4'}]},resultPreview:'{"mode":"text-to-video","prompt":"repeated prompt in raw result"}'}};
details.dc_video_portrait={...details.dc_video,...videoPortrait,presentation:{prompt:'将SSH握手过程制作成动画。展示客户端协商协议、交换密钥、建立加密通道。',parameters:[{key:'prompt',value:'完整提示词'},{key:'resolution',value:'1080P'},{key:'enable_audio',value:false}],result:{status:'completed',label:'工具返回完成',outputs:[{label:'SSH动画',path:'/workspace/ssh-handshake.mp4'}],parsed:{status:'completed',outputs:['/workspace/ssh-handshake.mp4']}}},portrait:{userRequest:{association:'candidate',userInput:'生成SSH视频'},steps:[videoPortrait],neighbors:[]}};
const sshPortrait={...weather,id:'dc_ssh_portrait',command:'ssh -p 2222 user@server.example.test uptime',destination:'server.example.test',summary:{action:'连接远程服务器并查询运行时间',target:'server.example.test',resultPreview:'运行时间2天 · 1位用户',outcome:{status:'ok',label:'命令退出码为0'}}};
details.dc_ssh_portrait={...details.dc_weather,...sshPortrait,presentation:{parameters:[{key:'command',value:sshPortrait.command},{key:'cwd',value:'/workspace'}],result:{status:'ok',label:'命令退出码为0',exitCode:0,stdout:'up 2 days, 1 user, load average: 0.10',stderr:'(empty)',parsed:null}},portrait:{userRequest:{association:'unavailable'},steps:[sshPortrait],neighbors:[]}};
const unknownWeather={...weatherPortrait,id:'dc_unknown_weather',summary:{action:'查询天气',resultPreview:'天气 Unrecognized Weather Description',outcome:{status:'unknown',facts:[{label:'天气',value:'Unrecognized Weather Description'}]}}};
details.dc_unknown_weather={...details.dc_weather_portrait,...unknownWeather,presentation:{parameters:[],result:{status:'unknown',facts:[{label:'天气',value:'Unrecognized Weather Description'}],parsed:{weatherDesc:'Unrecognized Weather Description'}}}};
const structuredPortrait={...sshPortrait,id:'dc_structured_portrait',summary:{action:'返回结构化条目',resultPreview:'',outcome:{status:'exit_zero',label:'命令退出码0'}}};
details.dc_structured_portrait={...details.dc_ssh_portrait,...structuredPortrait,presentation:{parameters:[],result:{status:'exit_zero',label:'命令退出码0',exitCode:0,stdout:'{\"items\":[1,2]}',parsed:{items:[1,2]},facts:[],outputs:[]}},portrait:{userRequest:{association:'unavailable'},steps:[structuredPortrait],neighbors:[]}};
let account={}, deferredSearch=null,deferredDetail=null,deferredQuestion=null,questionStatus='completed',newArrival=false;
const answer={perspective:'security',question:'这台设备有没有把凭据带入输入？',answer:{text:'在本地装配上下文发现凭据。实际网络发送仍需要请求证据。',basis:'原文出现位置',evidenceRefs:['E01']},observations:[{title:'凭据出现在系统背景',fact:'原文保留了凭据'}],evidence:[{ref:'E01',...contextRecord,text:originalArgument,truncated:false,rawUrl:'/model-data/raw?device=device-one&request=applens%3Acontext'}],coverage:{retainedRecords:41,searchedRecords:12,selectedRecords:1},gaps:['尚无可匹配 HTTP 请求'],candidates:[]};
const response=(data,status=200)=>({ok:status>=200&&status<300,status,json:async()=>data});
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const context={document:{getElementById:$,createElement:t=>new Element(t),createTextNode:t=>{const n=new Element('#text');n.textContent=t;return n;},querySelector:()=>new Element('a'),addEventListener:(k,f)=>documentListeners[k]=f,body,get activeElement(){return active;}},
 location:{origin:'http://localhost',pathname:'/model-data',search:''},sessionStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)},
 fetch:async(url,options)=>{requests.push({url,options});if(url==='/api/session') return response(account);
 if(url.startsWith('/api/data-center/search?')){const p=new URL(url,'http://localhost').searchParams;if(p.get('q')==='slow'&&deferredSearch) return deferredSearch.promise;if(p.get('q')==='badfield="x"')return response({error:'不支持字段 badfield'},400);const rows=p.get('q')==='portrait'?[weatherPortrait,videoPortrait,sshPortrait,structuredPortrait,unknownWeather]:p.get('q')==='192.0.2.1'?[addressRecord]:p.get('page')==='2'?(newArrival&&!p.get('snapshot')?[mention,video]:[video,contextRecord]):p.get('q')==='nothing'?[]:p.get('q')==='video'?[video]:[weather,mention];return response({items:rows,page:Number(p.get('page')),pageSize:20,total:p.get('q')==='nothing'?0:41,snapshot:p.get('snapshot')||'snapshot-before-new-arrival',hasMore:p.get('page')!=='2',facets:{devices:[{id:'device-one',name:'研发电脑'},{id:'device-two',name:'办公电脑'}]},coverage:{retainedRecords:41,searchedRecords:41,sources:[{collector:'applens',total:10},{collector:'sessionlens',total:31}],fullRetainedText:true,limitations:['应用日志不包含所有网络请求']}});}
 if(url.startsWith('/api/data-center/record?')){const id=new URL(url,'http://localhost').searchParams.get('id');if(id==='dc_weather'&&deferredDetail)return deferredDetail.promise;return response({item:details[id]||details.dc_weather});}
 if(url==='/api/collection/questions'){if(deferredQuestion)return deferredQuestion.promise;return response({id:'question-one',status:questionStatus,stage:'retrieving',result:answer});}
 if(url==='/api/collection/questions/question-one')return response({id:'question-one',status:'completed',result:answer});
 throw Error('Unexpected API '+url);},AbortController,URL,URLSearchParams,Intl,Date,Number,JSON,Object,String,Set,Map,Array,console,setTimeout,clearTimeout,addEventListener:(k,f)=>browserListeners[k]=f};
vm.createContext(context);vm.runInContext(js,context);
const settle=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
const submit=async(q)=>{$('dc-query').value=q;await $('dc-query').fire('input');await $('dc-search-form').fire('submit');await settle();};
const openRow=async(index)=>{await $('dc-results').children[index].fire('click');await settle();};
(async()=>{
 await settle();
 assert.equal($('dc-query').required,false,'default empty latest search is valid');
 assert.equal($('dc-count').textContent,'41 条匹配记录');assert.match($('dc-results').textContent,/Bash.*curl/s);assert.match($('dc-results').textContent,/上传账号：admin.*操作人员未确认/s);
 assert.ok($('dc-results').children.every(card=>find(card,node=>node.classes.has('dc-card-request')).length===1),'every raw search result retains a user-input area');assert.match($('dc-results').children[0].textContent,/用户输入未关联.*未找到对应用户输入/,'unassociated records state the missing input instead of concealing the field');
 assert.match($('dc-results').textContent,/正文提及的地址/);assert.ok(find($('dc-results'),n=>n.classes.has('dc-result-preview')).some(n=>n.textContent===mention.excerpt),'non-tool records retain a visible content preview');assert.doesNotMatch($('dc-results').textContent,/已确认风险/);
 assert.match($('dc-coverage-list').textContent,/AppLens：10.*SessionLens：31.*应用日志不包含/s);assert.equal(requests.some(r=>r.options.method==='POST'),false,'visitor first search sends no model request');
 await openRow(0);assert.equal($('dc-detail-title').textContent,weather.title);assert.match($('dc-detail-summary').textContent,/记录调用 Bash.*命令：curl.*参数中的访问对象/s);assert.doesNotMatch($('dc-detail-summary').textContent,/^\{/);assert.match($('dc-tool-facts').textContent,/工具Bash函数未采集执行命令curl/s);assert.match($('dc-arguments').textContent,/执行命令（command）.*https:\/\/weather\.example\.test\/Shanghai\?format=json/s);assert.match($('dc-arguments').textContent,/full original password ending 1234/);assert.match($('dc-return').textContent,/temperature25.*units/s);assert.match($('dc-raw').textContent,/call-weather/);assert.equal($('dc-raw-link').href,'/api/data-center/raw?id=dc_weather');assert.match($('dc-detail-matches').textContent,/本次搜索命中 · 工具参数/);assert.match($('dc-task-context').textContent,/候选需求.*尚未确认/s);assert.match($('dc-relations').textContent,/调用 → 对应返回.*唯一调用标识/s);assert.doesNotMatch($('dc-relations').textContent,/recorded_/);assert.doesNotMatch($('dc-task-context').textContent,/recorded_/);assert.match($('dc-raw').textContent,/recorded_unique_call_id/);assert.match($('dc-relations').children[0].textContent,/用户输入 · 查询天气.*已记录思路/s);assert.match($('dc-relations').children[1].textContent,/已记录思路.*工具调用/s);assert.match($('dc-relations').children[2].textContent,/工具调用.*工具返回/s);assert.match($('dc-record-gaps').textContent,/下一份模型输入/);assert.equal(body.style.overflow,'hidden');assert.equal(requests.some(r=>r.options.method==='POST'),false);
 await $('dc-close-detail').fire('click');assert.equal(body.style.overflow,'');await openRow(1);assert.match($('dc-content').textContent,/<script>window.leak=true<\/script>/);assert.equal(context.window?.leak,undefined);assert.match($('dc-record-boundary').textContent,/不能据此认定发生实际访问/);assert.match($('dc-relations').textContent,/不按相近时间或同一 Session/);
 newArrival=true;await $('dc-next').fire('click');await settle();assert.match(requests.at(-1).url,/page=2/);assert.match(requests.at(-1).url,/snapshot=snapshot-before-new-arrival/,'same query pages retain server snapshot across newly uploaded records');assert.doesNotMatch($('dc-results').textContent,/地址提及/);assert.match($('dc-results').textContent,/videoGen/);await openRow(0);assert.match($('dc-tool-facts').textContent,/工具MCP函数videoGen执行命令未采集/s);assert.match($('dc-arguments').textContent,/生成提示词（prompt）.*时长（秒）（seconds）/s);assert.match($('dc-record-gaps').textContent,/调用标识重复/);assert.match($('dc-return').textContent,/未采集到可唯一对应/);await openRow(1);assert.match($('dc-context-items').textContent,/系统背景.*full original password ending 1234/s);assert.match($('dc-record-gaps').textContent,/HTTP 请求头和响应未采集/);
 await submit('badfield="x"');assert.ok(!requests.at(-1).url.includes('snapshot='),'new query drops old snapshot');assert.equal($('dc-results').children.length,0);assert.match($('dc-error').textContent,/不支持字段/);assert.equal($('dc-query').value,'badfield="x"');assert.equal($('dc-recovery').hidden,false);assert.equal($('dc-coverage').textContent,'');
 await submit('192.0.2.1');assert.match($('dc-results').textContent,/参数目标https:\/\/192\.0\.2\.10\//);assert.match($('dc-results').textContent,/命中地址：192\.0\.2\.1 · 正文提及的地址/);const ipMark=find($('dc-results'),n=>n.tagName==='MARK')[0];assert.equal(ipMark.textContent,'192.0.2.1');assert.match(ipMark.parentElement.children[0].textContent,/192\.0\.2\.10.*investigate $/,'IP highlighter marks the exact comment occurrence, not a longer request target');
 await submit('nothing');assert.equal($('dc-empty').hidden,false);assert.equal($('dc-count').textContent,'0 条匹配记录');assert.equal($('dc-query').value,'nothing');
 deferredSearch=deferred();await submit('slow');assert.equal($('dc-progress').hidden,false);await submit('video');assert.match($('dc-results').textContent,/videoGen/);deferredSearch.resolve(response({items:[weather],total:1,page:1}));await settle();assert.match($('dc-results').textContent,/videoGen/);assert.doesNotMatch($('dc-results').textContent,/Bash/);deferredSearch=null;
 await submit('');deferredDetail=deferred();await openRow(0);assert.equal($('dc-detail-title').textContent,'正在读取记录');await openRow(1);assert.equal($('dc-detail-title').textContent,mention.title);deferredDetail.resolve(response({item:details.dc_weather}));await settle();assert.equal($('dc-detail-title').textContent,mention.title);deferredDetail=null;
 await submit('portrait');assert.match($('dc-results').textContent,/上报机器：研发电脑.*WorkBuddy.*SessionLens/s);assert.match($('dc-results').textContent,/23℃.*体感24℃.*湿度82%/s);assert.match($('dc-results').textContent,/返回被截取/);assert.match($('dc-results').textContent,/附近局部降雨（Patchy rain nearby）/);assert.match($('dc-results').textContent,/VideoGen.*DeferExecuteTool/s);assert.match($('dc-results').textContent,/生成音频关闭/);assert.match($('dc-results').textContent,/查看完整信息/);
 assert.match($('dc-results').children[1].textContent,/工具返回 1 个文件：ssh-handshake.mp4/);assert.doesNotMatch($('dc-results').children[1].textContent,/repeated prompt in raw result/);assert.equal(($('dc-results').children[1].textContent.match(/DeferExecuteTool/g)||[]).length,1,'identical executor/function labels are not repeated');
 await openRow(0);assert.equal($('dc-detail-title').textContent,'请求天气服务');assert.match($('dc-detail-summary').textContent,/上海：23℃/);assert.match($('dc-detail-facts').textContent,/上报机器研发电脑.*采集器SessionLens/s);assert.match($('dc-return').textContent,/气温23℃.*体感温度24℃.*湿度82%.*附近局部降雨（Patchy rain nearby）/s);assert.match($('dc-return').textContent,/2026-09-11.*22℃.*29℃/s);assert.match($('dc-task-context').textContent,/用户输入有原记录关联/);assert.doesNotMatch($('dc-related').textContent,/craft_mode/,'timeline displays the original user ask rather than the wrapper');assert.match($('dc-related').textContent,/查一下上海天气.*原记录有明确关联.*查看已记录思路原文.*当前记录.*候选关联/s);assert.equal($('dc-neighbor-details').hidden,false);assert.equal($('dc-neighbor-details').open,false);assert.match($('dc-neighbors').textContent,/同一源会话邻近记录.*归属未确认/s);assert.match($('dc-record-gaps').textContent,/1 条关联记录/);assert.equal($('dc-content-details').open,false);assert.equal($('dc-raw-details').open,false);
 const neighborButton=find($('dc-neighbors'),n=>n.tagName==='BUTTON')[0];await neighborButton.fire('click');await settle();assert.equal($('dc-detail-back').hidden,false);await $('dc-detail-back').fire('click');await settle();assert.equal($('dc-detail-title').textContent,'请求天气服务');await documentListeners.keydown({key:'Escape'});assert.equal($('dc-detail').hidden,true);assert.equal(active,$('dc-results').children[0],'close returns keyboard focus to originating search row');
 await openRow(1);assert.equal($('dc-prompt-section').hidden,false);assert.match($('dc-prompt').textContent,/协商协议、交换密钥/);assert.match($('dc-arguments').textContent,/分辨率.*1080P.*生成音频.*关闭/s);assert.doesNotMatch($('dc-arguments').textContent,/完整提示词/);assert.match($('dc-return').textContent,/返回的文件.*\/workspace\/ssh-handshake.mp4/s);assert.match($('dc-tool-facts').textContent,/执行器DeferExecuteTool/);assert.match($('dc-detail-outcome').textContent,/产物是否符合需求需另行核验/);assert.match($('dc-task-context').textContent,/候选需求/);
 videoPortrait.summary.outcome.status='failed';videoPortrait.summary.outcome.error='duration check failed';await submit('portrait');assert.match($('dc-results').children[1].textContent,/错误：duration check failed.*工具返回 1 个文件/s,'output files do not hide failure evidence');delete videoPortrait.summary.outcome.error;videoPortrait.summary.outcome.status='completed';await submit('portrait');
 await openRow(2);assert.match($('dc-return').textContent,/标准输出.*up 2 days, 1 user/s);assert.ok(!find($('dc-return'),n=>n.tagName==='H5').some(n=>n.textContent==='错误输出'),'empty stderr placeholder has no error section');assert.match($('dc-arguments').textContent,/ssh -p 2222.*执行目录/s);assert.equal($('dc-prompt-section').hidden,true,'changing record clears stale video prompt');await $('dc-detail-backdrop').fire('click');assert.equal($('dc-detail').hidden,true);
 await openRow(3);assert.match($('dc-return').textContent,/返回条目（items）.*2 个条目.*1.*2/s,'generic parsed stdout remains visible as readable fields');await $('dc-close-detail').fire('click');
 await openRow(4);assert.match($('dc-return').textContent,/天气Unrecognized Weather Description/,'unknown weather description keeps exact source text');await $('dc-close-detail').fire('click');
 // External raw URLs cannot redirect the original-record action to another origin.
 details.dc_ssh_portrait.rawUrl='https://untrusted.example.test/export';await openRow(2);assert.ok($('dc-raw-link').href.startsWith('/model-data/raw?'));assert.equal($('dc-query').value,'portrait');await $('dc-close-detail').fire('click');
 await $('dc-mode-investigate').fire('click');assert.equal($('dc-submit').disabled,true);await submit('有没有资料外发？');assert.match($('dc-error').textContent,/具体设备/);assert.equal(requests.some(r=>r.options.method==='POST'),false);$('dc-device').value='device-one';await $('dc-device').fire('change');await $('dc-search-form').fire('submit');assert.match($('dc-error').textContent,/需要登录/);
 // Reload actual script into the same synthetic DOM with signed identity, but no stored mode/consent.
 memory.clear();account={username:'admin',role:'admin',csrf:'synthetic-csrf'};for(const n of nodes.values()) n.listeners={};vm.runInContext(js,context);await settle();await $('dc-mode-investigate').fire('click');$('dc-device').value='device-one';await $('dc-device').fire('change');await submit('这台设备有没有把凭据带入输入？');assert.match($('dc-error').textContent,/先确认/);assert.equal(requests.some(r=>r.options.method==='POST'),false);assert.equal($('dc-collector').disabled,true,'unsupported semantic filters do not imply analysis scope');
 $('dc-share-confirmed').checked=true;await $('dc-search-form').fire('submit');await settle();const post=requests.find(r=>r.options.method==='POST');assert.deepEqual(JSON.parse(post.options.body),{deviceId:'device-one',question:'这台设备有没有把凭据带入输入？',scope:'global',perspective:'security',shareConfirmed:true});assert.equal(post.options.headers['X-CSRF-Token'],'synthetic-csrf');assert.equal($('dc-query').value,'这台设备有没有把凭据带入输入？');assert.match($('dc-answer').textContent,/装配上下文.*实际网络发送/s);assert.match($('dc-answer-coverage').textContent,/调查范围：研发电脑/);assert.equal($('dc-candidates').children.length,0,'safety answer works without business task candidates');assert.match($('dc-observations').textContent,/凭据出现在系统背景/);assert.match($('dc-answer-evidence-list').textContent,/full original password ending 1234/);assert.equal($('dc-answer-evidence').open,false);const ref=$('dc-answer-refs').children[0];await ref.fire('click');assert.equal($('dc-answer-evidence').open,true);
 // Editing a question cancels stale UI delivery and resets per-question consent.
 deferredQuestion=deferred();$('dc-query').value='旧问题';await $('dc-query').fire('input');$('dc-share-confirmed').checked=true;await $('dc-search-form').fire('submit');await settle();$('dc-query').value='新的任意问题';await $('dc-query').fire('input');assert.equal($('dc-share-confirmed').checked,false);deferredQuestion.resolve(response({id:'old-question',status:'completed',result:answer}));await settle();assert.equal($('dc-investigation-result').hidden,true);assert.equal($('dc-query').value,'新的任意问题');deferredQuestion=null;
 // Stop waits, retain the server job and retry GET only; do not accidentally charge a second analysis.
 questionStatus='running';$('dc-query').value='后续调查';await $('dc-query').fire('input');$('dc-share-confirmed').checked=true;await $('dc-search-form').fire('submit');await settle();await $('dc-cancel').fire('click');const posts=requests.filter(r=>r.options.method==='POST').length;$('dc-share-confirmed').checked=false;await $('dc-retry').fire('click');await settle();assert.equal(requests.filter(r=>r.options.method==='POST').length,posts);assert.match(requests.at(-1).url,/\/api\/collection\/questions\/question-one/);assert.equal($('dc-investigation-result').hidden,false);assert.equal($('dc-query').value,'后续调查');
 await $('dc-mode-search').fire('click');assert.equal($('dc-collector').disabled,false);assert.equal($('dc-query').required,false);await browserListeners.pagehide();
 assert.doesNotMatch(js,/innerHTML\s*=/,'raw content is always inserted as safe text');assert.doesNotMatch(js,/setInterval\s*\(/,'search does not continuously redraw or poll');assert.ok(html.includes('/product_ui.css'),'shared AgentPair style retained');assert.ok(html.includes('/model-data/raw'),'old raw viewer retained');
 console.log('PASS: Data Center search, full evidence, relations, scope/consent, paging, errors, race, stale answer and read-only retry. Synthetic DOM/API only; no network or model calls.');
})().catch(e=>{browserListeners.pagehide?.();console.error(e);process.exitCode=1;});
