// Local DOM fixture acceptance for the shared native AppLens content.
// Does not send data, start a collector, or automate a user's browser.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {parseHTML}=require(process.env.LINKEDOM_MODULE||'linkedom');
const shell=fs.readFileSync(path.join(__dirname,'../macos/collector.html'),'utf8');
const classifySource=fs.readFileSync(path.join(__dirname,'context.js'),'utf8');
const capture=fs.readFileSync(path.join(__dirname,'capture.html'),'utf8');
function run(source,extra={}){const {document,window}=parseHTML(source);window.matchMedia=()=>({matches:false});window.HTMLElement.prototype.focus=function(){};const context={window,document,requestAnimationFrame:()=>1,cancelAnimationFrame:()=>{},...extra};vm.runInNewContext(classifySource,context);vm.runInNewContext(source.match(/<script>([\s\S]*?)<\/script>/)[1],context);return {document,window};}
const captureDom=run(capture),actions=[];const {document,window}=parseHTML(shell);window.HTMLElement.prototype.focus=function(){};window.webkit={messageHandlers:{applens:{postMessage:value=>actions.push(value)}}};vm.runInNewContext(classifySource,{window,document});captureDom.window.postMessage=function(message){if(message.type==='applens-capture')captureDom.window.updateCapture(message.state);};Object.defineProperty(document.getElementById('captureScene'),'contentWindow',{value:captureDom.window});vm.runInNewContext(shell.match(/<script>([\s\S]*?)<\/script>/)[1],{window,document});
const $=id=>document.getElementById(id);const click=id=>$(id).onclick();let total=0;function check(name,fn){fn();total++;console.log('PASS '+name);}
const a='a'.repeat(64),b='b'.repeat(64),ha='1'.repeat(64),hb='2'.repeat(64);
const body1=JSON.stringify({model:'fixture-model',messages:[{role:'system',content:'# MEMORY.md\nprior project memory\n# Other\nnot memory'},{role:'user',content:'<user_query>查上海天气</user_query>'},{role:'assistant',content:'historical answer'},{role:'tool',content:'five returned weather records'}]});
const body2=JSON.stringify({messages:[{role:'user',content:'生成 SSH 动画 <script>window.bad=true</script>'},{role:'tool',content:'ssh-video.mp4'}]});
const first={id:a,bodySHA256:ha,source:'workbuddy_network_context',timestamp:1700000000,sessionName:'weather-fixture',bodyBytes:body1.length,receipt:false};const second={id:b,bodySHA256:hb,source:'workbuddy_generation_context',timestamp:1700000020,sessionName:'ssh-fixture',bodyBytes:body2.length,receipt:false};
const state={calls:[first,second],server:'https://fixture.invalid',deviceId:'fixture-device',active:true,connected:true,appRunning:true,localPath:'/fixture/local',captureBody:body1,captureBodyId:a,captureBodySHA256:ha};
check('desktop shell has local navigation, 164 px sidebar and no website account shell',()=>{assert(shell.includes('width:164px'));assert.equal(document.querySelectorAll('nav button').length,3);assert.equal(document.querySelector('.native-status').hidden,false);assert(!shell.includes('data-product='));assert(!shell.includes('macOS / Windows'));});
check('empty state is truthful and has no sample requests',()=>{assert.equal($('request-list').querySelectorAll('button').length,0);assert.equal($('raw-button').disabled,true);});
check('real request selects matching body and classifications',()=>{window.update(state);assert.equal($('request-list').querySelectorAll('button').length,2);assert.match($('request-task').textContent,/查上海天气/);assert.match($('categories').textContent,/记忆资料/);assert.match($('categories').textContent,/工具返回/);assert.match($('categories').textContent,/不是独立工具执行事件/);});
check('selecting second request requests native selected body',()=>{$('request-list').querySelectorAll('button')[1].onclick();assert.equal(actions.at(-1).action,'select');assert.equal(actions.at(-1).id,b);assert.doesNotMatch($('request-task').textContent,/查上海天气/);});
check('selected body updates without using weather context',()=>{window.update({...state,captureBody:body2,captureBodyId:b,captureBodySHA256:hb});assert.match($('request-task').textContent,/生成 SSH 动画/);assert.doesNotMatch($('categories').textContent,/five returned weather records/);assert.equal(document.querySelector('script[data-user]'),null);assert.equal(window.bad,undefined);});
check('mismatched body hash never displays another request content',()=>{window.update({...state,captureBody:body2,captureBodyId:b,captureBodySHA256:'wrong'});assert.match($('request-task').textContent,/读取/);assert.doesNotMatch($('categories').textContent,/ssh-video/);});
check('matching body restores selected evidence',()=>{window.update({...state,captureBody:body2,captureBodyId:b,captureBodySHA256:hb});click('raw-button');assert.equal($('inspector').hidden,false);assert.match($('proof').textContent,/ssh-video.mp4/);assert.match($('proof').textContent,new RegExp(b));assert.doesNotMatch($('proof').textContent,/weather-fixture/);});
check('evidence docks and closes without losing selection',()=>{assert.equal($('body-region').className,'body-region inspecting');click('close-proof');assert.equal($('inspector').hidden,true);assert.match($('request-title').textContent,/ssh-fixture/);});
check('category evidence retains raw behind explicit action',()=>{$('categories').querySelectorAll('button')[0].onclick();assert.equal($('proof').querySelector('pre').hidden,true);$('proof').querySelector('button').onclick();assert.equal($('proof').querySelector('pre').hidden,false);assert.equal($('proof').querySelector('button').getAttribute('aria-expanded'),'true');});
check('failed upload is not displayed as received',()=>{window.update({...state,captureBody:body2,captureBodyId:b,captureBodySHA256:hb,captureEvent:{id:b,bodySHA256:hb,phase:'failed'}});click('receipt-button');assert.match($('proof').textContent,/上传失败/);assert.doesNotMatch($('proof').textContent,/平台回执一致/);});
check('unconfirmed received event does not forge an acknowledgement',()=>{window.update({...state,captureBody:body2,captureBodyId:b,captureBodySHA256:hb,captureEvent:{id:b,bodySHA256:hb,phase:'received'}});click('receipt-button');assert.doesNotMatch($('proof').textContent,/平台回执一致/);});
check('receipt for selected request updates local and platform separately',()=>{window.update({...state,calls:[first,{...second,receipt:true}],captureBody:body2,captureBodyId:b,captureBodySHA256:hb});click('receipt-button');assert.match($('proof').textContent,/平台回执一致/);assert.match($('proof').textContent,/不证明模型服务/);assert.match($('sync-status').textContent,/1 \/ 2/);});
check('search uses metadata without changing selected evidence',()=>{$('request-search').value='weather';$('request-search').oninput();assert.equal($('request-list').querySelectorAll('button').length,1);assert.match($('request-title').textContent,/ssh-fixture/);$('request-search').value='no-match';$('request-search').oninput();assert.equal($('request-list').querySelectorAll('button').length,0);assert.match($('request-list').textContent,/没有匹配/);});
check('pause and platform actions preserve native bridge contracts',()=>{click('pause');assert.equal(actions.at(-1).action,'pause');click('platform-button');assert.equal(actions.at(-1).action,'call');assert.equal(actions.at(-1).id,b);click('records');assert.equal(actions.at(-1).action,'records');});
check('connection settings preserve saved destination and reject invalid origin',()=>{const nav=document.querySelectorAll('nav button');nav[2].onclick();assert.equal($('settings').hidden,false);assert.equal($('overview').hidden,true);assert.match($('local-path').textContent,/fixture/);$('server').value='http://untrusted.invalid';const count=actions.length;click('pair');assert.equal(actions.length,count);assert.match($('status-message').textContent,/HTTPS/);});
check('background refresh preserves a drafted platform address',()=>{$('server').value='https://new-fixture.invalid';$('server').oninput();window.update({...state,captureBody:body2,captureBodyId:b,captureBodySHA256:hb});assert.equal($('server').value,'https://new-fixture.invalid');});
check('initial and live data do not auto-play',()=>{assert.equal($('captureScene').hidden,true);assert.equal(captureDom.document.getElementById('capture-overlay').style.display,'none');});
check('window content has only local resources and IE11-compatible script syntax',()=>{assert(!/\b(?:fetch|WebSocket|XMLHttpRequest)\s*\(/.test(shell));assert(!/\b(?:let|const)\s|=>|\?\./.test(shell));assert(shell.includes('src="capture.html"'));});
console.log(total+' desktop interaction checks passed (DOM fixtures; not screenshot acceptance).');
