const $=id=>document.getElementById(id);
const pairFlow=new PairFlow($('pair-board'));
function el(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=String(text);if(cls)n.className=cls;return n;}
function card(title,role,time){const n=el('article',null,'card'),h=el('div',null,'card-head'),label=el('h3');label.append(el('span',role,'role '+(role==='Driver'?'driver':'')),document.createTextNode(title));h.append(label,el('small',time?new Date(time*1000).toLocaleTimeString('zh-CN',{hour12:false})+' · 产物写入':'等待产物'));n.append(h);return n;}
function showFindings(parent,items){for(const f of items){const n=el('div',null,'finding');n.append(el('span',f.confidence,'confidence'),el('strong',f.topic+' · '+f.claim),el('p',f.reason),el('div',(f.evidenceRefs||[]).join(' / '),'refs'));parent.append(n);}}
function raw(parent,data){const d=el('details'),p=el('pre',JSON.stringify(data,null,2));d.append(el('summary','查看结构化记录'),p);parent.append(d);}
function render(d){$('target').textContent=d.target;$('status').textContent=({analysis_completed:'本轮已完成',deployed:'协作中',failed:'运行失败'})[d.status]||d.status;$('tokens').textContent=d.stages.reduce((s,x)=>s+x.tokens,0).toLocaleString()+' tokens';$('calls').textContent=d.stages.filter(x=>x.complete).length+' 次调用 · deepseek-v3.2';$('price').textContent='¥'+Number(d.hourlyQuoteCNY||0).toFixed(2)+' / h';$('expiry').textContent=d.retainUntilUTC?new Date(d.retainUntilUTC).toLocaleTimeString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'})+' CST':'—';$('resource-state').textContent=d.hosts.every(x=>x.deleted)?'已释放（运行记录）':'保留中（运行记录）';$('run-id').textContent=d.runID;$('agents').replaceChildren();for(const a of d.hosts){const n=el('div',null,'agent '+a.role),info=el('div');info.append(el('strong',a.role==='navigator'?'Navigator · 规划与复核':'Driver · 采集与分析'),el('small',(a.ip||'启动中')+' · '+(a.deleted?'已释放':'已部署')));n.append(el('div',a.role==='navigator'?'N':'D','avatar'),info);$('agents').append(n);}
 $('timeline').replaceChildren();const p=card('候选方案与选择','Navigator',d.stages[0].artifactWrittenAt);for(const plan of d.plan.plans||[]){const n=el('div',null,'plan '+(plan.id===d.plan.selectedPlanID?'selected':''));n.append(el('label','方案 '+plan.id+(plan.id===d.plan.selectedPlanID?' · 已选择':'')),el('p',plan.approach));p.append(n);}p.append(el('p',d.plan.reason||'等待规划结果'));$('timeline').append(p);const a=card('公开证据采集与分析','Driver',d.stages[1].artifactWrittenAt);a.append(el('p','已记录 '+d.evidence.length+' 条证据。仅执行固定、低频公开读取。'));showFindings(a,d.driverFindings);$('timeline').append(a);const r=card('独立复核与修改','Navigator',d.stages[2].artifactWrittenAt);for(const c of d.corrections)r.append(el('p',c));r.append(el('p','人工核验提示：'+d.humanReview));$('timeline').append(r);
 $('evidence-count').textContent=d.evidence.length+' 条可追溯记录';$('evidence-list').replaceChildren();for(const e of d.evidence){const n=card(e.ref+' · '+({http_root:'首页响应',public_asset:'静态资源',ip_registration:'IP 注册信息'})[e.kind],'Driver');n.append(el('p',e.url||e.registryURL||''));if(e.title)n.append(el('p','页面标题：'+e.title));if(e.status)n.append(el('p','HTTP '+e.status));if(e.country)n.append(el('p','注册国家：'+e.country+' · 不是物理位置'));raw(n,e);$('evidence-list').append(n);} $('human-review').textContent=d.humanReview;$('corrections').replaceChildren();for(const c of d.corrections)$('corrections').append(el('div',c,'notice'));$('findings').replaceChildren();const f=card('Navigator 复核输出（保留原始判断）','Navigator',d.stages[2].artifactWrittenAt);showFindings(f,d.reviewFindings);raw(f,{corrections:d.corrections,findings:d.reviewFindings});$('findings').append(f);}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==b.dataset.view));}));
let last='';async function refresh(){try{const r=await fetch('/api/run',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json(),s=JSON.stringify(d);if(s!==last){render(d);last=s;}$('connection').textContent='● 已同步 · '+new Date().toLocaleTimeString('zh-CN',{hour12:false});$('error').classList.add('hidden');}catch(e){$('connection').textContent='● 连接中断';$('error').textContent='无法同步 Navigator。显示的是上次成功读取的记录；机器释放后页面会停止服务。';$('error').classList.remove('hidden');}}refresh();setInterval(refresh,5000);
const renderSnapshot=render;
render=d=>{renderSnapshot(d);const messages=[{role:'navigator',stage:'plan',round:1,answer:{summary:d.plan.reason,...d.plan}},{role:'driver',stage:'driver',round:1,answer:{summary:d.driverFindings.map(f=>f.claim).join('；'),findings:d.driverFindings}},{role:'navigator',stage:'review',round:1,answer:{summary:d.corrections.join('；'),findings:d.reviewFindings,corrections:d.corrections}}];pairFlow.update({round:1,status:d.status,snapshot:true,messages,events:d.stages.filter(s=>s.complete).map(s=>({round:1,kind:'stage_completed',stage:s.id,at:s.artifactWrittenAt}))});};
