(() => {
 const $=id=>document.getElementById(id),node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
 let csrf='',role='viewer',username='',devices=[],device=null,selected=null,busy=false;
 const taskKey=()=>device&&username?`agentpair-device-task:${username}:${device.id}`:null;
 async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:data?JSON.stringify(data):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}
 const notice=e=>{$('notice').textContent=e.message||String(e);};
 let plan=null;
 function canAnalyze(){$('make-plan').disabled=busy||!device?.online||!selected||!csrf;$('analyze').disabled=busy||!plan||!$('share').checked;$('analyze').textContent=plan?'确认计划并开始分析':'确认计划并开始分析';}
 async function refresh(){try{const session=await api('/api/session');csrf=session.csrf||'';role=session.role;username=session.username||'';$('login-toggle').textContent=csrf?(username||'当前用户')+' · 已登录':'登录 / 注册';$('logout').hidden=!csrf;$('pair').disabled=!csrf;if(!csrf){devices=[];device=null;selected=null;const empty=node('div','');empty.className='device-empty';empty.append(node('strong','尚未连接设备'),node('p','登录或注册后，下载安装包并输入一次性配对码，设备上线后即可选择应用发起分析。'));const login=node('button','登录 / 注册并接入设备');login.type='button';login.onclick=()=>{$('login-panel').hidden=false;$('login-panel').scrollIntoView({behavior:'smooth',block:'start'});};empty.append(login);$('device-list').replaceChildren(empty);render();return;}devices=(await api('/api/devices')).items;device=devices.find(d=>d.id===device?.id)||devices[0]||null;
   if(role==='user'){const b=await api('/api/balance');$('login-toggle').textContent=session.username+' · 剩余额度 ¥'+b.remainingCNY.toFixed(4)+'（预估预扣）';}
   // Preserve selection only while its actual inventory identity still exists.
   if(selected){const rows=device?.snapshot[selected.kind]||[];selected=rows.findIndex(x=>JSON.stringify(x)===selected.identity)>=0?{...selected,index:rows.findIndex(x=>JSON.stringify(x)===selected.identity)}:null;}
   $('device-list').replaceChildren();if(!devices.length)$('device-list').append(node('p','尚无设备。点击上方「接入 Windows 设备」开始。'));
   for(const d of devices){const b=node('button',d.name);b.className='device'+(d.id===device?.id?' selected':'');b.append(node('small',(d.collectors||[]).map(c=>c.name+' · '+c.records+' 条').join(' / ')||'尚无采集器数据'));const status=node('span',d.online?'● 在线':'● 离线');status.className='status'+(d.online?'':' offline');b.append(status,node('small',(d.snapshot?.os||'等待采集')+' · '+(d.lastSeen?'最近心跳 '+new Date(d.lastSeen*1000).toLocaleString():'等待首次采集')));b.onclick=()=>{device=d;selected=null;invalidatePlan();render();refresh();};$('device-list').append(b);}render();await renderCurrentTask();
 }catch(e){notice(e);}}
 function detailRow(label,value){const row=node('div','');row.className='detail-row';row.append(node('span',label),node('strong',value));return row;}
 const installLink=node('a','远程安装软件');installLink.href='/software';document.querySelector('main')?.prepend(installLink);
 async function renderCurrentTask(){const box=$('current-task-content'),key=taskKey(),id=device?.currentTaskId||(key&&localStorage.getItem(key));box.replaceChildren();$('current-task').hidden=!device;if(!device){box.append(node('p','选择设备后查看任务'));return;}if(!id){box.append(node('p','尚未从这台设备发起任务。发起后可查看采集进度、团队协作和分析结果。'));return;}try{const task=await api('/api/tasks/'+encodeURIComponent(id));if(!device||taskKey()!==key)return;box.append(node('strong',task.title),node('p',({'queued':'等待执行','running':'正在协作','completed':'已完成','blocked':'验收未通过，可继续推进','failed':'执行失败'})[task.status]||task.status));const a=node('a','查看任务过程与结果 →');a.href='/?task='+encodeURIComponent(id);box.append(a);}catch(_){box.append(node('p','任务记录暂时不可读取，请到任务中心查看。'));}}
 async function renderAndroidTasks(){const box=$('android-task-list');if(!box||!device||device.snapshot?.os!=='Android')return;try{const data=await api('/api/devices/tasks');box.replaceChildren();const rows=data.items.filter(t=>t.deviceId===device.id);if(!rows.length){box.append(node('p','这台手机还没有云端任务。'));return;}for(const task of rows){const card=node('article','');card.className='device-subcard';const p=task.payload||{},r=task.result||{};card.append(node('strong',p.title||'Android 云端任务'),node('p',p.goal||''),node('small',`状态：${({queued:'等待手机领取',assigned:'手机已领取',received:'手机已接收',running:'手机处理中',completed:'已提交结果',blocked:'阻塞',failed:'失败'})[task.state]||task.state}`));if(r.summary)card.append(node('p','手机回执：'+r.summary));box.append(card);}}catch(error){box.replaceChildren(node('p','任务状态暂时不可读取：'+error.message));}}
 function invalidatePlan(){plan=null;$('plan').hidden=true;$('share').checked=false;canAnalyze();}
 function render(){const snap=device?.snapshot||{};$('device-details').replaceChildren();$('device-details').hidden=!device;$('current-task').hidden=!device;$('inventory-panel').hidden=!device;$('android-tasks').hidden=!device||snap.os!=='Android';$('revoke').disabled=!device||!csrf;plan=null;$('plan').hidden=true;
   window.agentpairSelectedDevice=device||null;window.dispatchEvent(new CustomEvent('agentpair:device-selected',{detail:device||null}));document.querySelector('.analysis').hidden=device?.snapshot?.os==='Android';if(device){$('device-details').append(node('h3','设备详情'),detailRow('注册记录',device.registrationCount>1?'同一设备 · '+device.registrationCount+' 条历史注册已归并':'单一注册'),detailRow('基础信息',`${snap.os||'等待采集'} / ${snap.architecture||'未知架构'}`),detailRow('已采集能力',`进程信息 ${(snap.processes||[]).length} 项 · 应用清单 ${(snap.applications||[]).length} 项`),detailRow('数据来源',(device.collectors||[]).map(c=>c.name+' · '+c.records+' 条').join(' / ')||'尚无采集器记录'),detailRow('上传范围','已上报的设备元数据、上下文及会话事件'));for(const error of snap.errors||[])$('device-details').append(node('p',error));}
   $('selection').value=selected?(device.snapshot[selected.kind][selected.index]?.name||''):'';renderPicker();renderItems();canAnalyze();if(device&&snap.os==='Android')renderAndroidTasks();}
 function renderPicker(){const picker=$('application-picker');picker.replaceChildren(node('option','请选择应用或进程'));picker.firstChild.value='';for(const kind of ['applications','processes']){const group=node('optgroup','');group.label=kind==='applications'?'已安装应用':'运行进程';(device?.snapshot[kind]||[]).forEach((x,index)=>{const option=node('option',x.name+(kind==='processes'?' · PID '+x.pid:''));option.value=kind+':'+index;option.selected=selected?.kind===kind&&selected.index===index;group.append(option);});picker.append(group);}picker.disabled=!device;if(device){const link=node('a','上下文与会话采集数据 →');link.href='/model-data?device='+encodeURIComponent(device.id);link.className='download';$('device-details').append(link);}}
 $('application-picker').onchange=e=>{const [kind,index]=e.target.value.split(':');const x=device?.snapshot[kind]?.[Number(index)];selected=x?{kind,index:Number(index),identity:JSON.stringify(x)}:null;invalidatePlan();render();};
 function renderItems(){const kind=$('kind').value,query=$('search').value.toLowerCase();$('items').replaceChildren();const rows=device?.snapshot[kind]||[];let count=0;
   rows.forEach((x,index)=>{if(!x.name.toLowerCase().includes(query))return;count++;const b=node('button',x.name);b.className='item'+(selected?.kind===kind&&selected.index===index?' selected':'');b.append(node('small',kind==='processes'?`PID ${x.pid} · 父进程 ${x.parentPid}`:`${x.version||'版本未知'} · ${x.publisher||'发布者未知'} · ${(x.processNames||[]).length} 个匹配进程名称`));b.onclick=()=>{selected={kind,index,identity:JSON.stringify(x)};invalidatePlan();render();};$('items').append(b);});if(!count)$('items').append(node('p','暂无匹配数据'));}
 $('login-toggle').onclick=()=>{$('login-panel').hidden=!$('login-panel').hidden;};
 $('register-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('password')!==f.get('confirmation')){notice('两次密码不一致');return;}const button=e.target.querySelector('button');button.disabled=true;try{await api('/api/register',{username:f.get('username'),password:f.get('password')});e.target.reset();$('login-panel').hidden=true;notice('注册成功，请点击「接入 Windows 设备」获取配对码。');await refresh();}catch(err){notice(err);}finally{button.disabled=false;}};
 $('logout').onclick=async()=>{try{await api('/api/logout',{});$('pair-panel').hidden=true;$('pair-command').textContent='';await refresh();}catch(err){notice(err);}};
 $('login-form').onsubmit=async e=>{e.preventDefault();try{const form=new FormData(e.target);await api('/api/login',{username:form.get('username'),password:form.get('password')});e.target.password.value='';$('login-panel').hidden=true;$('notice').textContent='';await refresh();}catch(err){notice(err);}};
 $('pair').onclick=async()=>{try{const pair=await api('/api/devices/pairing',{});$('pair-panel').hidden=false;$('pair-command').textContent=pair.code;setTimeout(()=>{$('pair-command').textContent='配对码已过期，请重新生成。';},600000);}catch(e){notice(e);}};
 $('refresh').onclick=refresh;$('kind').onchange=renderItems;$('search').oninput=renderItems;
 $('android-task-form').onsubmit=async e=>{e.preventDefault();if(!device||device.snapshot?.os!=='Android')return;const submit=e.target.querySelector('button');submit.disabled=true;try{await api('/api/devices/dispatch',{deviceId:device.id,task:{title:$('android-task-title').value.trim(),goal:$('android-task-goal').value.trim()}});$('android-task-state').textContent='已下发，等待手机上线领取。';e.target.reset();$('android-task-title').value='手机云端交互测试';await renderAndroidTasks();}catch(error){$('android-task-state').textContent=error.message;}finally{submit.disabled=false;}};
 $('revoke').onclick=async()=>{if(!confirm('解除绑定将停止此设备上传，并清除平台上的当前快照。已创建的分析任务会保留。'))return;try{await api('/api/devices/revoke',{deviceId:device.id});selected=null;await refresh();}catch(e){notice(e);}};
 $('make-plan').onclick=async()=>{if(!selected||!device||busy)return;busy=true;canAnalyze();try{plan=await api('/api/devices/plan',{deviceId:device.id,kind:selected.kind,index:selected.index,selected:JSON.parse(selected.identity),goal:$('goal').value,scopes:[...document.querySelectorAll('.scope input:checked')].map(x=>x.id==='scope-processes'?'processes':'applications')});const box=$('plan-content');box.replaceChildren(node('p',`目标：${plan.name} · ${plan.scopes.join('、')}`));const ol=node('ol');for(const step of plan.steps)ol.append(node('li',step));box.append(ol,node('p','验收：'+plan.acceptance.join('；')),node('p','限制：'+plan.limitations.join('；')));$('plan').hidden=false;$('share').onchange=canAnalyze;canAnalyze();}catch(err){notice(err);}finally{busy=false;canAnalyze();}};
 $('analysis-form').onsubmit=async e=>{e.preventDefault();if(!plan||busy)return;busy=true;canAnalyze();try{const result=await api('/api/devices/confirm',{planId:plan.id,shareConfirmed:$('share').checked});const task=await api('/api/tasks/'+result.taskId);device.currentTaskId=task.id;const key=taskKey();if(key&&task.id)localStorage.setItem(key,task.id);$('result').replaceChildren(node('p','已创建分析任务：'+task.title));const a=node('a','查看该任务的团队执行与结果 →');a.href='/?task='+encodeURIComponent(task.id);$('result').append(a);$('notice').textContent='';await renderCurrentTask();}catch(err){notice(err);}finally{busy=false;canAnalyze();}};
 $('goal').addEventListener('input',invalidatePlan);for(const input of document.querySelectorAll('.scope input'))input.addEventListener('change',invalidatePlan);
 refresh();setInterval(()=>{if(!busy&&!plan)refresh();},10000);
})();
