(()=>{'use strict';
const $=id=>document.getElementById(id),set=(id,v)=>$(id).textContent=v,params=new URLSearchParams(location.search);
const globalView=params.get('scope')!=='mine';
let data=null,selected=null,view='categories',tab='original',loading=false,findAt=-1,csrf='',detailGeneration=0,loadGeneration=0,initialRequest=params.get('request')||'',readerScope='',reviewGeneration=0;
const option=(v,t)=>{const o=document.createElement('option');o.value=v;o.textContent=t;return o;};
const call=()=>data?.calls.find(c=>c.id===$('request').value);
const items=()=> (data?.items||[]).filter(i=>i.requestId===$('request').value);
const bytes=n=>n>=1024?(n/1024).toFixed(1)+' KB':n+' B';
const dateText=t=>Number.isFinite(t)&&t>0?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(t*1000))+'（北京时间）':'时间未采集';
function scopeText(){const device=$('device').selectedOptions[0]?.textContent||'未选择设备';set('search-scope','搜索范围：'+device+' / '+$('collector').selectedOptions[0].textContent);set('question-device',device);}
async function api(p){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);try{const r=await fetch(p,{credentials:'same-origin',cache:'no-store',signal:controller.signal}),d=await r.json();if(!r.ok)throw Error(d.error||'读取失败');return d;}catch(e){throw Error(e.name==='AbortError'?'读取超时，请点击重试':e.message);}finally{clearTimeout(timeout);}}
function failure(e){set('status',e.message);set('empty','读取失败：'+e.message);$('empty').hidden=false;set('receipt','读取失败');$('rows').replaceChildren();set('detail-title','未能读取采集记录');set('original','读取失败：'+e.message);$('original').hidden=false;$('basis-text').hidden=true;}
const endpoint=()=> (globalView?'/api/audit/model-data/':'/api/devices/model-data/')+encodeURIComponent($('device').value);
const rawScope=()=> $('device').value+'|'+$('collector').value;
async function hydrate(){const n=++detailGeneration,id=$('request').value,scope=rawScope();if(!id){selected=null;render();return;}set('empty','正在读取选中调用…');$('empty').hidden=false;set('receipt','正在读取选中调用');set('original','正在读取选中调用…');set('detail-title','正在读取选中调用');$('rows').replaceChildren();try{const detail=await api(endpoint()+'?collector='+encodeURIComponent($('collector').value)+'&request='+encodeURIComponent(id));if(n!==detailGeneration||scope!==rawScope())return;data=data||{calls:[],items:[]};data.items=detail.items;const record=detail.calls[0],index=data.calls.findIndex(c=>c.id===id);if(record){if(index>=0)data.calls[index]=record;else data.calls.push(record);if(record.application&&![...$('application').children].some(o=>o.value===record.application))$('application').append(option(record.application,record.application));if(record.sessionId&&![...$('session').children].some(o=>o.value===record.sessionId))$('session').append(option(record.sessionId,record.sessionName||record.sessionId));}readerScope=scope;selected=items().find(i=>i.id===selected?.id)||items()[0]||null;render();set('status','');}catch(e){if(n===detailGeneration)failure(e);}}
function choose(i){selected=i;tab='original';findAt=-1;render();}
function readerText(){return tab==='full'||view==='full'?call()?.body||'无原文':selected?.rawContent||'请选择分类内容';}
function render(){
 const c=call(),q=$('search').value.toLowerCase(),list=items().filter(i=>[i.name,i.category,i.rawContent].join(' ').toLowerCase().includes(q));
 set('source',c?.collector==='sessionlens'?'来源：SessionLens · '+c.application:c?.source==='workbuddy_network_context'?'来源：AgentReins 完整 HTTP 请求体通道':'来源：WorkBuddy generation');set('capture-layer',c?.collector==='sessionlens'?'源日志会话事件':c?.source==='workbuddy_network_context'?'同一 HTTP 请求体':'应用记录的装配上下文');set('destination',c?.destination?'目标：'+c.destination:'目标 / 网络发送未验证');set('model','模型：'+(c?.model||'未采集'));$('model').title=c?.modelEvidence||'未取得模型证据';set('size',c?bytes(c.bodyBytes)+' · '+dateText(c.timestamp):'暂无调用');
 set('truncate',c?.wireLengthMatched?'捕获请求体长度校验一致':c?.truncated?'源记录已触发截断':c?.recordStatus==='parseable'?'源记录可解析 · 未触发截断':'源记录未验证');set('completeness',c?.wireLengthMatched?'SHA256 及声明/捕获长度一致；不代表远端处理成功':c?.truncated?'源记录已触发截断，缺失内容未知':c?.recordStatus==='parseable'?'JSON 可解析、未触发截断；网络请求完整性未验证':'源记录未验证');
 set('coverage',c?.collector==='sessionlens'?'这是一条源日志事件，可查看提问、回复、已记录思路或工具数据；不代表完整模型请求。':c?.truncated?'这份源记录可能被截断。展示全部已采集内容，不补造缺失内容。':c?.source==='workbuddy_network_context'?'沿用 AgentReins 完整请求体采集，保留原文，不采模型返回或独立工具事件。':'当前采集层是应用装配记录，非网络抓包；分类不改变原文。');
 set('receipt',c?.bodySHA256?'平台已入库 · SHA256 '+c.bodySHA256.slice(0,12)+'…':'暂无回执');
 $('rows').replaceChildren();$('empty').hidden=!!list.length;set('empty',c?'没有匹配的分类内容':'尚无模型输入记录');
 for(const i of list){const tr=document.createElement('tr');tr.tabIndex=0;tr.classList.toggle('selected',selected?.id===i.id);
 for(const value of [i.category,i.source,bytes(i.bodyBytes),i.classificationBasis,'未独立验证']){const td=document.createElement('td');td.textContent=value;tr.append(td);}
 tr.onclick=()=>choose(i);tr.onkeydown=e=>{if(e.key==='Enter'){choose(i);}};$('rows').append(tr);}
 set('detail-title',tab==='full'||view==='full'?'完整已采集模型输入':selected?.name||'选择一类上下文');
 set('original',readerText());$('original').hidden=tab==='basis';$('basis-text').hidden=tab!=='basis';
 set('basis-text',selected?.classificationBasis||'请选择数据项');set('basis',selected?.classificationBasis||'完整原文未分类替换');
 set('position',selected?'消息 '+(selected.messageIndex+1)+' / 内容块 '+(selected.blockIndex+1)+' / 字符 '+selected.charStart+'–'+selected.charEnd:'');
 set('raw',JSON.stringify(selected?{...selected,rawContent:undefined}:c?{...c,body:undefined}:{},null,2));
 for(const b of $('detail-tabs').children)b.classList.toggle('selected',b.dataset.tab===tab);
 for(const b of $('view-tabs').children)b.classList.toggle('selected',b.dataset.view===view);
}
async function requests(preferred){const previous=typeof preferred==='string'?preferred:$('request').value,session=$('session').value;const calls=(data?.calls||[]).filter(c=>(session==='all'||c.sessionId===session)&&($('application').value==='all'||c.application===$('application').value));
 $('request').replaceChildren(...calls.map(c=>option(c.id,dateText(c.timestamp)+' · '+(c.collectorName||'')+' · '+(c.modelEvidence||c.id.slice(0,8)))));
 if(!calls.length)$('request').append(option('','暂无调用'));if(calls.some(c=>c.id===previous))$('request').value=previous;
 await hydrate();}
async function load(){scopeText();if(!$('device').value){set('empty','尚无可查看的采集设备');set('receipt','暂无记录');return;}const n=++loadGeneration,scope=rawScope(),requested=initialRequest;initialRequest='';++detailGeneration;loading=true;try{const metadata=await api(endpoint()+'?summary=1&collector='+encodeURIComponent($('collector').value));if(n!==loadGeneration||scope!==rawScope())return;const preferred=requested||(readerScope===scope?$('request').value:'');data=metadata;const app=$('application').value;const apps=[...new Set(data.calls.map(c=>c.application).filter(Boolean))];$('application').replaceChildren(option('all','全部应用'),...apps.map(a=>option(a,a)));if(apps.includes(app))$('application').value=app;
 const previous=$('session').value,sessions=new Map(data.calls.map(c=>[c.sessionId,c.sessionName]));
 $('session').replaceChildren(option('all','全部会话'),...[...sessions].map(([id,name])=>option(id,name)));
 if(sessions.has(previous))$('session').value=previous;if(preferred&&!data.calls.some(c=>c.id===preferred)){$('request').replaceChildren(option(preferred,'正在定位指定采集记录…'));await hydrate();}else await requests(preferred);
 }catch(e){if(n===loadGeneration)failure(e);}finally{if(n===loadGeneration)loading=false;}}
$('review-session').onclick=async()=>{const current=call(),n=++reviewGeneration,scope=rawScope();if(!current?.sessionId){set('review-status','当前记录没有会话标识，无法可靠关联。');return;}set('review-status','正在读取会话记录…');$('review-results').replaceChildren();try{const summary=await api(endpoint()+'?summary=1&collector='+encodeURIComponent($('collector').value));if(n!==reviewGeneration||scope!==rawScope())return;const rows=summary.calls.filter(c=>c.sessionId===current.sessionId).sort((a,b)=>a.timestamp-b.timestamp);const counts={};for(const c of rows){const type=c.modelEvidence||c.recordType||'记录';counts[type]=(counts[type]||0)+1;}set('review-status','当前查询窗口中找到 '+rows.length+' 条同会话记录：'+Object.entries(counts).map(([k,v])=>k+' '+v+' 条').join('，')+'。会话可能包含多个任务；不等于完整任务或模型交互次数。');data.calls=summary.calls;for(const c of rows){const b=document.createElement('button');b.type='button';b.className='search-hit';b.textContent=dateText(c.timestamp)+' · '+(c.collectorName||'')+' · '+(c.modelEvidence||c.recordType||'记录')+' → 查看内容';b.onclick=async()=>{if(n!==reviewGeneration||scope!==rawScope())return;$('request').replaceChildren(option(c.id,c.modelEvidence||c.id));await hydrate();};$('review-results').append(b);}}catch(error){if(n===reviewGeneration&&scope===rawScope())set('review-status',error.message);}};
let searchGeneration=0;
$('history-search-form').onsubmit=async e=>{e.preventDefault();const q=$('history-query').value.trim(),n=++searchGeneration,device=$('device').value,collector=$('collector').value;if(!q||!device)return;set('history-status','正在搜索已接收的记录…');$('history-results').replaceChildren();try{const result=await api(endpoint()+'?collector='+encodeURIComponent(collector)+'&q='+encodeURIComponent(q));if(n!==searchGeneration||device!==$('device').value||collector!==$('collector').value)return;set('history-status','找到 '+result.items.length+' 条相关记录。'+result.coverage);for(const hit of result.items){const b=document.createElement('button');b.type='button';b.className='search-hit';const title=document.createElement('strong');title.textContent=(hit.collector==='sessionlens'?'SessionLens':'AppLens')+' · '+hit.source+' · '+hit.kind+' · '+dateText(hit.timestamp);const excerpt=document.createElement('span');const at=hit.excerpt.toLowerCase().indexOf(q.toLowerCase());if(at>=0){const mark=document.createElement('mark');mark.textContent=hit.excerpt.slice(at,at+q.length);excerpt.append(document.createTextNode(hit.excerpt.slice(0,at)),mark,document.createTextNode(hit.excerpt.slice(at+q.length)));}else excerpt.textContent=hit.excerpt;const action=document.createElement('small');action.textContent='查看原文与证据 →';b.append(title,excerpt,action);b.onclick=async()=>{if(n!==searchGeneration||device!==$('device').value||collector!==$('collector').value)return;++detailGeneration;data={calls:[{id:hit.id}],items:[]};$('request').replaceChildren(option(hit.id,hit.kind));await hydrate();$('detail-title').scrollIntoView({block:'start',behavior:'smooth'});};$('history-results').append(b);}}catch(error){if(n===searchGeneration)set('history-status',error.message);}};
function clearHistoryScope(){++searchGeneration;++reviewGeneration;$('history-results').replaceChildren();set('history-status','范围已切换，请重新搜索当前范围的记录。');$('review-results').replaceChildren();set('review-status','');}
$('collector').onchange=()=>{clearHistoryScope();selected=null;load();};$('application').onchange=requests;
$('device').onchange=()=>{clearHistoryScope();clearPending();cancelQuestion('设备已切换，请重新询问当前设备的任务。');previousQuestionId='';pendingQuestion=null;$('question-result').hidden=true;$('question-error').hidden=true;selected=null;load();};$('session').onchange=requests;$('request').onchange=hydrate;$('search').oninput=render;
$('view-tabs').onclick=e=>{const b=e.target.closest('button');if(b){view=b.dataset.view;render();}};
$('detail-tabs').onclick=e=>{const b=e.target.closest('button');if(b){tab=b.dataset.tab;render();}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(readerText());set('status','已复制当前原文');}catch(e){set('status','复制失败，请选择原文后复制');}};
$('export').onclick=()=>{const c=call();if(!c)return;const url=URL.createObjectURL(new Blob([c.body],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='model-input-'+c.id.replace(':','-').slice(0,24)+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('text-search').oninput=()=>{findAt=-1;};
$('find').onclick=()=>{const text=readerText(),q=$('text-search').value;if(!q)return;let at=text.toLowerCase().indexOf(q.toLowerCase(),findAt+1);if(at<0)at=text.toLowerCase().indexOf(q.toLowerCase());set('match-status',at<0?'未找到':'字符 '+at);if(at<0)return;findAt=at;
 const pre=$('original');pre.replaceChildren(document.createTextNode(text.slice(0,at)));const mark=document.createElement('mark');mark.textContent=text.slice(at,at+q.length);pre.append(mark,document.createTextNode(text.slice(at+q.length)));mark.scrollIntoView({block:'nearest'});};

// The assistant has its own request lifecycle. Reading raw records never resets its question.
let questionGeneration=0,questionRun=null,lastQuestion=null,questionAuthReady=false,previousQuestionId='',pendingQuestion=null;
const draftKey='agentpair.collection-question.draft',pendingKey='agentpair.collection-question.pending';
function savePending(value){pendingQuestion=value?{...value,scope:globalView?'global':'mine'}:null;try{if(pendingQuestion)sessionStorage.setItem(pendingKey,JSON.stringify(pendingQuestion));else sessionStorage.removeItem(pendingKey);}catch(_){} }
function clearPending(){savePending(null);}
async function restorePending(){try{const saved=JSON.parse(sessionStorage.getItem(pendingKey)||'null');if(saved&&typeof saved.id==='string'&&typeof saved.device==='string'&&typeof saved.question==='string'&&saved.scope===(globalView?'global':'mine')&&saved.device===$('device').value&&csrf){savePending(saved);await retryQuestion();}}catch(_){clearPending();}}
const arr=value=>Array.isArray(value)?value:[];
const textValue=value=>typeof value==='string'?value:typeof value==='number'?String(value):'';
const node=(tag,className,text)=>{const element=document.createElement(tag);if(className)element.className=className;if(text!==undefined)element.textContent=textValue(text);return element;};
function questionAuth(session){questionAuthReady=true;csrf=session.csrf||'';$('question-submit').disabled=!csrf;$('collection-question').disabled=!csrf;$('question-auth').replaceChildren();if(csrf){$('question-auth').textContent='使用平台已配置的模型理解相关记录；回答附原文依据，无法确认的关联会单独标明。';}else{$('question-auth').append(document.createTextNode('游客可查看原文；询问任务需要登录。'),Object.assign(document.createElement('a'),{href:'/',textContent:'前往任务中心登录'}));}}
function association(value){const status=textValue(value).toLowerCase();if(['exact','matched','identity','hard','direct','linked'].includes(status))return {text:'标识一致',className:''};if(status==='supported')return {text:'语义关联',className:'inferred'};if(['semantic','inferred','likely'].includes(status))return {text:'语义推断',className:'inferred'};if(['confirmed','completed','delivered','done'].includes(status))return {text:'已关联 · 结果待核验',className:'inferred'};if(['rejected','conflict','unmatched'].includes(status))return {text:'未确认关联',className:'pending'};return {text:'待确认',className:'pending'};}
function basisLabel(value){return {recorded:'采集原文',inferred:'语义推断',unknown:'证据不足'}[value]||textValue(value);}
function associationChip(value){const label=association(value);return node('span','association-chip '+label.className,label.text);}
function collectorName(value){return textValue(value).toLowerCase()==='sessionlens'?'SessionLens':'AppLens';}
function recordKind(value){const labels={user_message:'用户提问',user:'用户提问',assistant_message:'Agent 回复',assistant:'Agent 回复',reasoning:'已记录思路',thinking:'已记录思路',tool_call:'工具调用',tool_result:'工具返回',function_call:'工具调用',function_call_output:'工具返回',file_snapshot:'会话文件快照',session_metadata:'会话元信息',context:'模型输入上下文',model_context:'模型输入上下文'};return labels[value]||textValue(value)||'采集记录';}
function originalLink(recordId,collector,label='查看原文 ↗'){if(!recordId)return null;const id=textValue(recordId),kind=collector==='sessionlens'||id.startsWith('sessionlens:')?'sessionlens':'applens',link=node('a','record-link',label);const query=new URLSearchParams({device:questionRun?.device||lastQuestion?.device||$('device').value,collector:kind,request:id,scope:globalView?'global':'mine'});link.href='/model-data?'+query.toString();link.target='_blank';link.rel='noopener';return link;}
function addOriginal(container,recordId,collector,label){const link=originalLink(recordId,collector,label);if(link)container.append(link);}
function explanation(text){if(!text)return null;const detail=node('details','association-explanation');detail.append(node('summary','', '为什么关联到这个需求？'),node('p','',text));return detail;}
function renderCandidate(candidate,index){
 const card=node('details','task-candidate');card.open=false;const summary=node('summary'),overview=node('div','candidate-overview');overview.append(node('strong','candidate-title',candidate.title||'未命名需求'));const meta=node('div','candidate-meta');meta.append(associationChip(candidate.status));if(candidate.source)meta.append(node('span','',candidate.source));if(Number.isFinite(candidate.turnsCount))meta.append(node('span','',candidate.turnsCount+' 轮讨论'));if(Number.isFinite(candidate.recordCount))meta.append(node('span','',candidate.recordCount+' 条证据'));overview.append(meta);if(candidate.reason)overview.append(node('span','candidate-reason',candidate.reason));summary.append(overview);card.append(summary);const content=node('div','candidate-content');
 const requirements=arr(candidate.requirements);if(requirements.length){content.append(node('h4','','需求如何逐步明确'));const list=node('ol','requirement-list');const relations={request:'原始需求',discussion:'讨论需求',resume:'恢复需求',unresolved:'关联待确认',origin:'原始需求',initial:'原始需求',followup:'补充要求',continuation:'继续同一需求',approval:'确认执行',confirmation:'确认执行',correction:'修改要求',execution:'执行要求',revision:'修改要求'};for(const requirement of requirements){const row=node('li','requirement-row');row.append(node('span','requirement-label',relations[requirement.relation]||'相关提问'),node('p','',requirement.text||'这条提问没有可读正文。'));addOriginal(row,requirement.recordId,'sessionlens','核对这次提问 ↗');const why=explanation(requirement.reason);if(why)row.append(why);list.append(row);}content.append(list);}
 const stages=arr(candidate.stages);if(stages.length){content.append(node('h4','','执行过程'));const timeline=node('div','task-stages');stages.forEach((stage,number)=>{const item=node('article','task-stage'),heading=node('div','stage-heading');heading.append(node('span','stage-number',number+1),node('strong','',stage.title||'已记录的步骤'));item.append(heading);if(stage.kind)item.append(node('span','requirement-label',recordKind(stage.kind)));item.append(node('p','',stage.text||'没有可读的步骤摘要。'));addOriginal(item,stage.recordId,stage.collector);if(stage.basis)item.append(node('p','stage-basis','依据：'+basisLabel(stage.basis)));timeline.append(item);});content.append(timeline);}
 const contexts=arr(candidate.contexts);if(contexts.length){content.append(node('h4','','与模型输入的关联'));const rows=node('div','context-associations');for(const context of contexts){const row=node('div','context-row');row.append(associationChip(context.status),node('p','',context.reason||'没有采集到足够的关联依据。'));addOriginal(row,context.recordId,'applens','核对输入上下文 ↗');rows.append(row);}content.append(rows);}
 const gaps=arr(candidate.gaps).filter(value=>textValue(value));if(gaps.length){const notice=node('div','evidence-gap');notice.append(node('strong','','仍缺少的证据'));const list=node('ul');for(const gap of gaps)list.append(node('li','',gap));notice.append(list);content.append(notice);}
 if(!requirements.length&&!stages.length&&!contexts.length)content.append(node('p','answer-basis','目前只有候选记录，尚不能还原完整需求与执行过程。'));
 card.append(content);return card;
}
function renderQuestionResult(result){
 if(!result||typeof result!=='object'||!textValue(result.answer?.text))throw Error('平台没有返回可读的回答，请重试。');
 const evidence=arr(result.evidence),candidates=arr(result.candidates);set('question-asked','你的问题：'+(lastQuestion?.question||result.question||''));set('question-answer-text',result.answer.text);set('question-answer-basis',result.answer.basis?'依据：'+basisLabel(result.answer.basis)+' · Agent 的交付声明不等于结果已核验。':'回答仅依据已上报记录；Agent 的交付声明不等于结果已核验。');$('question-answer-refs').replaceChildren();$('question-candidates').replaceChildren();$('question-evidence-list').replaceChildren();$('question-evidence').open=false;
 const gaps=[...new Set(arr(result.gaps).map(textValue).filter(Boolean))];$('question-gaps-list').replaceChildren(...gaps.map(gap=>node('li','',gap)));$('question-gaps').hidden=!gaps.length;$('question-gaps').open=false;set('question-gaps-title','本次仍有 '+gaps.length+' 项证据缺口 · 展开核对');
 const references=new Map();evidence.forEach((fragment,index)=>{const item=node('article','evidence-fragment');item.id='question-fragment-'+index;const head=node('div','fragment-head');head.append(node('span','fragment-label','证据 '+(index+1)+' · '+collectorName(fragment.collector)+' · '+recordKind(fragment.kind)));addOriginal(head,fragment.recordId,fragment.collector,'打开完整原文 ↗');item.append(head,node('p','',fragment.text||'这条记录没有可读正文。'));if(fragment.truncated)item.append(node('span','fragment-truncated','分析使用了原文片段，可打开完整原文核对。'));$('question-evidence-list').append(item);if(fragment.ref)references.set(fragment.ref,{item,index});});
 const answerRefs=arr(result.answer.evidenceRefs);let shownRefs=0;for(const ref of answerRefs){const fragment=references.get(ref);if(!fragment)continue;const button=node('button','','依据 '+(fragment.index+1));button.type='button';button.onclick=()=>{$('question-evidence').open=true;fragment.item.scrollIntoView({block:'center',behavior:'smooth'});};button.hidden=shownRefs++>=6;$('question-answer-refs').append(button);}
 if(shownRefs>6){const more=node('button','','展开全部 '+shownRefs+' 条回答依据');more.type='button';more.onclick=()=>{for(const button of $('question-answer-refs').children)button.hidden=false;more.hidden=true;};$('question-answer-refs').append(more);}
 set('question-evidence-count',evidence.length?evidence.length+' 条':'暂无可读片段');$('question-evidence').hidden=!evidence.length;
 if(candidates.length){$('question-candidates').append(node('h3','',candidates.length===1?'关联到的需求':'相关需求 · '+candidates.length+' 个候选'));candidates.forEach((candidate,index)=>$('question-candidates').append(renderCandidate(candidate,index)));}else{$('question-candidates').append(node('p','answer-basis','没有找到可可靠关联的需求。可补充项目名称、需求描述或时间，再次询问。'));}
 const coverage=result.coverage||{},scope=[];if(Number.isFinite(coverage.indexedRecords)&&Number.isFinite(coverage.totalRecords))scope.push('已索引 '+coverage.indexedRecords+' / '+coverage.totalRecords+' 条记录');if(Number.isFinite(coverage.selectedRecords))scope.push('本次核对 '+coverage.selectedRecords+' 条');if(coverage.indexComplete===false)scope.push('历史索引仍在补充，可能存在未命中的任务');scope.push('同一会话可能包含多个需求，关联结果可通过原文核对');set('question-coverage',scope.join(' · '));$('question-result').hidden=false;
}
function isCurrent(run){return questionRun===run&&run.generation===questionGeneration;}
function endQuestion(run){if(!isCurrent(run))return;clearTimeout(run.pollTimer);clearTimeout(run.deadlineTimer);run.controller.abort();questionRun=null;$('question-progress').hidden=true;$('question-result').setAttribute('aria-busy','false');$('question-submit').textContent='询问任务';}
function questionFailure(run,message){if(!isCurrent(run))return;endQuestion(run);set('question-error-text',message);$('question-retry').textContent=pendingQuestion?.device===$('device').value?'重新查看结果':'重试此问题';$('question-error').hidden=false;}
function cancelQuestion(message){const run=questionRun;if(run)endQuestion(run);++questionGeneration;if(message){set('question-stage',message);set('question-auth',message);}}
async function questionApi(path,run,payload){const controller=new AbortController(),abort=()=>controller.abort();run.controller.signal.addEventListener('abort',abort,{once:true});const timer=setTimeout(abort,30000);try{const response=await fetch(path,{method:payload?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:payload?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:payload?JSON.stringify(payload):undefined});let result;try{result=await response.json();}catch(_){throw Error('平台返回异常，未能读取任务回答，请重试。');}if(!response.ok){if(!payload&&[403,404].includes(response.status))clearPending();if(response.status===401){csrf='';questionAuth({});}throw Error(textValue(result.error)||'任务助手请求失败（HTTP '+response.status+'）。');}return result;}catch(error){if(error.name==='AbortError'&&isCurrent(run))throw Error('读取任务回答超时，请重试此问题。');throw error;}finally{clearTimeout(timer);run.controller.signal.removeEventListener('abort',abort);}}
function stageLabel(stage){const labels={queued:'已收到问题，等待检索…',indexing:'正在更新任务索引…',retrieving:'正在查找相关需求…',linking:'正在关联多轮讨论与执行…',analyzing:'正在核对上下文与会话证据…',reviewing:'正在检查回答与原文是否一致…'};return labels[stage]||textValue(stage)||'正在关联需求、讨论与执行证据…';}
async function receiveQuestion(job,run){if(!isCurrent(run))return;if(job.id){run.jobId=job.id;savePending({id:job.id,device:run.device,question:run.question});}if(job.status==='completed'){renderQuestionResult(job.result);previousQuestionId=run.jobId||'';clearPending();endQuestion(run);return;}if(job.status==='failed'){clearPending();questionFailure(run,textValue(job.error)||'本次未能完成检索，请重试此问题。');return;}if(!['running','queued','pending'].includes(job.status)||!run.jobId){questionFailure(run,'平台没有返回可继续查询的任务状态，请重试。');return;}set('question-stage',stageLabel(job.stage));run.pollTimer=setTimeout(async()=>{if(!isCurrent(run))return;try{const next=await questionApi('/api/collection/questions/'+encodeURIComponent(run.jobId),run);await receiveQuestion(next,run);}catch(error){if(isCurrent(run))questionFailure(run,error.message);}},2000);}
function beginQuestion(question,device,jobId=''){cancelQuestion();const run={generation:questionGeneration,device,question,jobId,controller:new AbortController(),pollTimer:null,deadlineTimer:null};questionRun=run;lastQuestion={device,question};$('collection-question').value=question;try{sessionStorage.setItem(draftKey,question);}catch(_){}$('question-result').hidden=true;$('question-error').hidden=true;$('question-progress').hidden=false;$('question-result').setAttribute('aria-busy','true');set('question-stage',jobId?'正在重新读取此问题的结果…':'正在查找与问题相关的已采集任务…');$('question-submit').textContent='重新提问';run.deadlineTimer=setTimeout(()=>questionFailure(run,run.jobId?'已等待 5 分钟，模型可能仍在处理。问题与任务编号已保留，可重新查看结果，无需重复发送。':'已等待 5 分钟，尚未收到任务编号。问题已保留，请稍后再试。'),300000);return run;}
async function askQuestion(question){const device=$('device').value;if(!csrf){questionAuth({});return;}if(!question||!device){set('question-error-text',!device?'请先选择有采集记录的设备。':'请输入你想了解的问题。');$('question-retry').textContent='重试此问题';$('question-error').hidden=false;return;}if(pendingQuestion?.device===device&&pendingQuestion.question===question){await retryQuestion();return;}clearPending();const run=beginQuestion(question,device);try{const job=await questionApi('/api/collection/questions',run,{deviceId:device,question,scope:globalView?'global':'mine',previousQuestionId:previousQuestionId||undefined});await receiveQuestion(job,run);}catch(error){if(isCurrent(run))questionFailure(run,error.message);}}
async function retryQuestion(){if(pendingQuestion?.device===$('device').value){const pending=pendingQuestion,run=beginQuestion(pending.question,pending.device,pending.id);try{await receiveQuestion(await questionApi('/api/collection/questions/'+encodeURIComponent(pending.id),run),run);}catch(error){if(isCurrent(run))questionFailure(run,error.message);}return;}askQuestion($('collection-question').value.trim()||lastQuestion?.question||'');}
$('collection-question-form').onsubmit=event=>{event.preventDefault();askQuestion($('collection-question').value.trim());};
$('question-retry').onclick=retryQuestion;
$('question-cancel').onclick=()=>{cancelQuestion('已停止等待。问题已保留，可修改后重新询问。');if(pendingQuestion){set('question-error-text','已停止本页等待。后台检索可能仍在处理，可重新查看结果。');$('question-retry').textContent='重新查看结果';$('question-error').hidden=false;}};
$('collection-question').oninput=()=>{try{sessionStorage.setItem(draftKey,$('collection-question').value);}catch(_){}};
try{$('collection-question').value=sessionStorage.getItem(draftKey)||'';}catch(_){}
window.addEventListener('pagehide',()=>cancelQuestion());

(async()=>{try{if(['applens','sessionlens'].includes(params.get('collector')))$('collector').value=params.get('collector');const session=await api('/api/session');set('identity',session.username?session.username+' · 已登录':'未登录');questionAuth(session);if(!session.csrf&&!globalView)throw Error('请先登录，或从全局审计打开公开原文');
 const list=await api(globalView?'/api/audit/devices':'/api/devices');$('device').replaceChildren(...list.items.sort((a,b)=>(b.lastActivity||0)-(a.lastActivity||0)).map(d=>option(d.id,d.name+' · '+d.id.slice(0,8)+(d.online?' · 最近有活动':' · 暂无近期活动'))));
 if(list.items.some(d=>d.id===params.get('device')))$('device').value=params.get('device');else if(!params.get('device')){try{const saved=JSON.parse(sessionStorage.getItem(pendingKey)||'null');if(saved?.scope===(globalView?'global':'mine')&&list.items.some(d=>d.id===saved.device))$('device').value=saved.device;}catch(_){}}await load();await restorePending();
 }catch(e){failure(e);if(!questionAuthReady)set('question-auth','登录状态未能确认，请刷新页面后再询问。');}})();
const retry=document.createElement('button');retry.textContent='重试读取';retry.type='button';retry.onclick=load;$('status').after(retry);
const audit=document.createElement('a');audit.textContent='交互审计与安全检测 ↗';audit.href='/model-security';$('identity').parentElement.append(audit);audit.onclick=()=>{audit.href='/model-security?device='+encodeURIComponent($('device').value)+(call()?.collector==='applens'?'&request='+encodeURIComponent(call().id):'');};
setInterval(()=>{if(!document.hidden&&!loading&&!$('text-search').value&&!$('history-query').value)load();},60000);
})();
