(()=>{
 const $=id=>document.getElementById(id);let items=[],selected='',system='全部',session={},taskId='',devices=[],downloadReady=false;
 const labels={cached:'已缓存 · 已校验',registered:'已登记',downloading:'下载中',failed:'下载失败',interrupted:'下载中断',missing:'缓存文件缺失',source_recipe:'软件源方案'};
 const bytes=n=>n>=1024**3?(n/1024**3).toFixed(2)+' GB':(n/1024**2).toFixed(1)+' MB';
 async function api(path,data){const response=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':session.csrf}:{},body:data?JSON.stringify(data):undefined});let result;try{result=await response.json();}catch(_){throw Error("服务暂时无法返回数据（HTTP "+response.status+"）。请保留本次输入并核对状态，再重试。");}if(!response.ok)throw Error(result.error||'请求失败');return result;}
 function draw(){const rows=$('rows');rows.replaceChildren();const filtered=items.filter(x=>(system==='全部'||x.platform===system)&&x.name.toLowerCase().includes($('search').value.toLowerCase()));$('empty').hidden=!!filtered.length;
  for(const item of filtered){const row=document.createElement('tr');row.className=item.id===selected?'selected':'';const name=document.createElement('td');const strong=document.createElement('strong');strong.textContent=item.name;const small=document.createElement('small');small.textContent=item.platform;name.append(strong,document.createElement('br'),small);const version=document.createElement('td');version.textContent=item.version||'软件源版本';const state=document.createElement('td');state.textContent=labels[item.cacheState]||'未知';const action=document.createElement('td');const button=document.createElement('button');button.textContent='详情';button.onclick=()=>{selected=item.id;$('install-box').hidden=true;draw();};action.append(button);row.append(name,version,state,action);rows.append(row);}
  const item=items.find(x=>x.id===selected);if(!item)return;$('detail-name').textContent=item.name;$('detail-status').textContent=labels[item.cacheState]||'未知';$('fields').replaceChildren();for(const [k,v] of [['系统',item.platform],['版本',item.version||'Ubuntu 软件源版本'],['大小',item.bytes?bytes(item.bytes):'尚无下载回执'],['安装方式',item.installer],['SHA256',item.sha256||'由 apt 软件源校验']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;$('fields').append(dt,dd);}
  $('version').textContent=item.version||'安装时由 Ubuntu apt 解析版本及依赖';$('verified').textContent=item.verifiedAt?'最近校验：'+new Date(item.verifiedAt*1000).toLocaleString('zh-CN'):'尚无缓存校验回执';$('preload').hidden=session.role!=='admin'||item.platform!=='Windows';$('preload').disabled=item.cacheState==='downloading';$('install').hidden=session.role!=='admin';$('permission').textContent=session.role==='admin'?'安装前再次校验；版本验证通过才算完成。':'软件目录公开可见；软件安装目前需管理员下发。';
 }
 async function load(){const result=await api('/api/packages');items=result.items;downloadReady=result.node.downloadReady===true;if(!items.some(x=>x.id===selected))selected=items[0]?.id||'';$('summary').textContent=items.length+' 个软件方案 · '+items.filter(x=>x.cacheState==='cached').length+' 个已缓存 · 缓存占用 '+bytes(result.node.bytes);$('node-name').textContent=result.node.name||'尚未配置缓存 Driver';$('node-state').textContent=({online:'在线 · '+(downloadReady?'Driver HTTPS 直连就绪':'直连未验证，安装走官方源'),unconfigured:'未配置',unreachable:'不可达 · 缓存状态未确认'})[result.node.state];$('node-usage').textContent='已发布安装包：'+bytes(result.node.bytes);draw();}
 $('search').oninput=draw;document.querySelectorAll('[data-system]').forEach(b=>b.onclick=()=>{system=b.dataset.system;document.querySelectorAll('[data-system]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();});$('refresh').onclick=()=>load().catch(e=>$('notice').textContent=e.message);
 $('preload').onclick=async()=>{try{await api('/api/packages/prepare',{softwareId:selected});$('notice').textContent='缓存任务已提交，等待 Driver 下载校验';await load();}catch(e){$('notice').textContent=e.message;}};
 $('install').onclick=async()=>{try{devices=(await api('/api/devices')).items;const item=items.find(x=>x.id===selected);$('device').replaceChildren();for(const d of devices.filter(x=>x.snapshot?.os===item.platform&&x.online)){const o=document.createElement('option');o.value=d.id;o.textContent=d.name;$('device').append(o);}$('confirm').disabled=!$('device').options.length;$('source').textContent=item.cacheState==='cached'&&downloadReady?'优先从缓存 Driver 下载；不可达时回退官方源。':'从官方来源下载；缓存尚不可用。';$('install-box').hidden=false;}catch(e){$('notice').textContent=e.message;}};
 $('confirm').onclick=async()=>{if(!confirm('确认在此设备安装所选软件？'))return;try{const r=await api('/api/software/install',{deviceId:$('device').value,softwareId:selected});taskId=r.taskId;$('progress').textContent='任务已排队，等待设备领取';}catch(e){$('progress').textContent=e.message;}};
 async function poll(){try{if(items.some(x=>x.cacheState==='downloading'))await load();if(taskId){const r=(await api('/api/devices/tasks')).items.find(x=>x.taskId===taskId);if(r){$('progress').textContent=r.state+' · '+(r.result?.summary||'等待设备回执');if(['completed','failed','blocked'].includes(r.state))taskId='';}}}catch(e){$('notice').textContent=e.message;}}
 api('/api/session').then(s=>{session=s;$('identity').textContent=s.role==='admin'?'管理员 · 已登录':'公开软件目录';$('register-link').hidden=s.role!=='admin';return load();}).catch(e=>$('notice').textContent=e.message);setInterval(poll,3000);
})();
