/* Team operations console. All content is derived from persisted task records. */
(() => {
  const make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=String(text);if(cls)n.className=cls;return n;};
  const role=x=>({navigator:'Navigator',driver:'Driver',user:'用户'})[x]||x;
  const time=x=>x?new Date(x).toLocaleTimeString('zh-CN',{hour12:false}):'时间未记录';
  const stages={plan:'规划任务',driver:'执行工作',review:'复核与交付',explore:'独立探索',review_peer:'交叉复核',revise:'修订结果'};
  const title=e=>e.text||e.summary||({stage_started:'开始'+(stages[e.stage]||e.stage),stage_completed:'完成'+(stages[e.stage]||e.stage),handoff_requested:'交接工作上下文',branch_handoff:'共享发现',branch_handoff_processed:'已处理交接',rework:'验收后继续返工',stopped:'任务已停止'})[e.kind]||e.kind;
  const terminal=new Set(['completed','failed','cancelled','interrupted','blocked']);
  let selectedJob=null;let task=null,selected='Navigator',tab='messages',follow=false,signature='',unread=0,scope='all';
  const root=make('section',null,'team-console');root.id='team-console';root.hidden=true;
  root.innerHTML='<div class="tc-heading"><div><div class="tc-breadcrumb">任务 <span>›</span> 团队工作台</div><h1></h1><p></p></div><span class="tc-task-status"></span></div><div class="tc-overview"><section class="tc-canvas"><div class="tc-canvas-label">团队工作流 <small>点击节点查看工作 · 点击连线消息查看往返记录</small></div><div class="tc-map"><svg aria-hidden="true"></svg><div class="tc-nodes"></div><div class="tc-edge-messages"></div></div></section><section class="tc-activity"><h2>团队动态</h2><div></div></section></div><section class="tc-work"><div class="tc-work-heading"><h2></h2><span></span></div><div class="tc-tabs" role="tablist" aria-label="节点详情"></div><div class="tc-work-body"><section class="tc-jobs"></section><section class="tc-detail"></section></div><div class="tc-work-footer"><span class="tc-new"></span><label><input type="checkbox"> 跟随最新</label></div></section>';
  $('pair-board').before(root);
  document.body.classList.add('team-console-page');
  const stylesheet=make('link');stylesheet.rel='stylesheet';stylesheet.href='/team_console.css';document.head.append(stylesheet);
  // Preserve existing forms/access control, but place publishing in the top bar.
  document.querySelector('.account-actions').prepend($('new-task'));
  document.querySelector('.brand small').textContent='TEAM WORKSPACE';
  document.querySelector('.crumb').textContent='任务 / 团队工作台';
  const resource=document.querySelector('.resource-drawer');if(resource)document.querySelector('.account-actions').prepend(resource);
  const priorAccess=applyAccess;applyAccess=()=>{priorAccess();document.querySelector('.hero').classList.toggle('hidden',!!task);};
  const tabs=root.querySelector('.tc-tabs');
  for(const [key,label] of [['work','当前工作'],['messages','往返消息'],['logs','日志与产物']]){const b=make('button',label);b.type='button';b.role='tab';b.dataset.tab=key;b.onclick=()=>{pauseFollow();tab=key;renderDetails();};tabs.append(b);}
  const updateNotice=root.querySelector('.tc-new');updateNotice.setAttribute('role','button');updateNotice.tabIndex=0;updateNotice.title='点击更新记录，保持当前阅读位置';updateNotice.onclick=()=>{unread=0;renderDetails();};updateNotice.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();updateNotice.click();}};
  const pauseFollow=()=>{follow=false;root.querySelector('input').checked=false;};
  root.addEventListener('click',e=>{if(e.target.closest('summary'))pauseFollow();});
  root.querySelector('.tc-detail').addEventListener('wheel',pauseFollow,{passive:true});
  root.querySelector('input').onchange=e=>{follow=e.target.checked;if(follow){unread=0;renderDetails();}};
  function events(){return task.events||[];}
  function belongs(e,node){return role(e.role||e.from||e.message?.from)===node||role(e.to||e.message?.to)===node;}
  function nodeEvents(node){return events().filter(e=>role(e.role||e.from)===node);}
  function lens(node){return(task.applens||[]).find(n=>n.name===node);}
  function nodes(){const names=new Set(['Navigator']);if(task.engineeringMethod==='parallel'){names.add('Driver A');names.add('Driver B');}else names.add('Driver');for(const e of events()){for(const raw of [e.role,e.from,e.to,e.message?.from,e.message?.to]){const n=role(raw);if(n&&n!=='用户'&&n!=='system')names.add(n);}}for(const m of task.messages||[]){const n=role(m.role);if(n&&n!=='用户')names.add(n);for(const n of Object.keys(m.answer?.branches||{}))names.add(n);}for(const n of task.applens||[])names.add(n.name);if([...names].some(n=>/^Driver /.test(n)))names.delete('Driver');return [...names];}
  function assignment(name){const op=(task.operations?.nodes||[]).find(n=>n.name===name&&n.address);if(op)return{address:op.address,kind:op.kind};const event=events().filter(e=>e.kind==='node_assigned'&&role(e.role)===name).at(-1);if(event)return{address:event.address||event.intelligence?.address,kind:event.nodeKind||event.intelligence?.nodeKind};if(name==='Driver'&&task.engineeringMethod==='pair'){const node=(window.agentpairNodes||[]).find(n=>n.id==='linux-driver');if(node)return{address:node.address,kind:'persistent_linux'};}return null;}
  function state(node){const device=lens(node);if(device)return{status:device.online?'设备在线':'设备离线',text:`${device.application} · 采集 ${device.completedSteps}/${device.totalSteps} 项`,at:new Date(device.lastSeen*1000).toISOString()};const es=nodeEvents(node).filter(e=>e.round===task.round),last=es.at(-1);if(!last)return{status:'等待',text:'尚无执行事件',at:null};let status='执行中';if(/failed|stopped|interrupted/.test(last.kind))status='失败';else if(/completed|processed/.test(last.kind))status='已返回';else if(last.kind==='tool_result')status=last.receipt?.ok===false?'工具失败':'工具已返回';if(terminal.has(task.status)&&status==='执行中')status='本轮已结束';return{status,text:title(last),at:last.at};}
  function payload(parent,value){if(value==null)return;if(typeof value==='string'){parent.append(make('p',value));return;}if(Array.isArray(value)){const list=make('ul');for(const x of value){const li=make('li');payload(li,x);list.append(li);}parent.append(list);return;}const labels={summary:'内容',steps:'计划步骤',findings:'发现',corrections:'修正意见',nextSteps:'下一步',questions:'待确认',claim:'结论',topic:'主题',reason:'依据',evidenceRefs:'证据引用',request:'任务要求',code:'代码',finalAnswer:'交付答复',arguments:'输入',result:'返回',error:'错误',status:'状态',stdout:'标准输出',stderr:'错误输出',exitCode:'退出码'};for(const [k,v]of Object.entries(value)){const block=make('div',null,'tc-field');block.append(make('small',labels[k]||k));if(typeof v==='string')block.append(make(k==='code'?'pre':'p',v));else if(typeof v!=='object'||v===null)block.append(make('p',String(v)));else{const d=make('details');d.open=['arguments','result','steps','corrections'].includes(k);d.append(make('summary',Array.isArray(v)?`${v.length} 项`:'展开内容'));payload(d,v);block.append(d);}parent.append(block);}}
  function messages(){const list=new Map();for(const [index,e]of events().entries()){const p=e.message||(e.kind==='handoff_requested'?{id:'legacy-'+index,from:e.from,to:e.to,summary:e.summary||e.text||'已记录上下文交接'}:null);if(!p?.id)continue;let row=list.get(p.id);if(!row){row={...p,round:e.round,at:e.at,receipts:[],status:'交接已记录'};list.set(p.id,row);}if(e.kind==='worker_received')row.status='执行端已接收';if(e.kind==='branch_handoff_processed')row.status='已处理';row.receipts.push(e);}for(const e of events()){const row=list.get(e.messageId);if(!row)continue;row.receipts.push(e);if(e.kind==='worker_received')row.status='执行端已接收';if(['stage_completed','branch_handoff_processed','worker_completed'].includes(e.kind))row.status='已处理';if(e.kind==='worker_failed')row.status='失败';}
    const rows=[...list.values()];for(const [index,m]of (task.messages||[]).entries()){if(m.role==='user')continue;rows.push({id:'output-'+index,from:m.role,to:'任务记录',round:m.round,at:m.at,content:m.answer||m.text,summary:m.answer?.summary||m.text||'',status:'阶段产出 · '+(stages[m.stage]||m.stage||''),receipts:[]});}return rows.sort((a,b)=>String(a.at).localeCompare(String(b.at)));}
  function select(node,nextTab){selected=node;selectedJob=null;scope='node';if(nextTab)tab=nextTab;renderGraph();renderDetails();}
  function renderGraph(){const names=nodes(),nodeBox=root.querySelector('.tc-nodes'),map=root.querySelector('.tc-map');nodeBox.replaceChildren();const workers=names.filter(n=>n!=='Navigator'),columns=Math.max(1,Math.min(3,Math.ceil(workers.length/2))),rows=Math.max(1,Math.ceil(workers.length/columns)),width=Math.max(680,map.clientWidth),height=Math.max(300,rows*140+70),positions={};map.style.height=height+'px';
    function add(name,x,y,review=false){const s=review?{status:terminal.has(task.status)?(labels[task.status]||task.status):'等待证据',text:'对照验收条件与执行证据'}:state(name),b=make('button',null,'tc-node'+(name===selected&&!review?' selected':''));b.type='button';b.dataset.node=name;const head=make('div',null,'tc-node-title'),badge=make('span',review?'✓':name==='Navigator'?'N':name.replace('Driver','').trim()||'D','tc-avatar');head.append(badge,make('strong',review?'复核与交付':name));b.append(head,make('p',s.text),make('small',s.status,'tc-node-state'));const assigned=!review&&assignment(name);if(assigned?.address)b.append(make('small',(assigned.kind==='persistent_linux'?'常驻 Linux · ':'Linux 节点 · ')+assigned.address,'tc-node-address'));b.style.left=x+'px';b.style.top=y+'px';b.onclick=()=>select(name,review?'logs':undefined);nodeBox.append(b);positions[review?'review':name]={x:x+76,y:y+50};}
    const reviewX=width-170,driverStart=190,driverEnd=reviewX-170;add('Navigator',12,height/2-50);workers.forEach((n,i)=>add(n,driverStart+(i%columns)*(driverEnd-driverStart)/Math.max(1,columns-1)+(columns===1?(driverEnd-driverStart)/2:0),38+Math.floor(i/columns)*140));add('Navigator',reviewX,height/2-50,true);const fullWidth=Math.max(width,reviewX+166);nodeBox.style.width=fullWidth+'px';const svg=map.querySelector('svg');svg.setAttribute('viewBox',`0 0 ${fullWidth} ${height}`);svg.style.width=fullWidth+'px';svg.replaceChildren();const defs=document.createElementNS('http://www.w3.org/2000/svg','defs');defs.innerHTML='<marker id="tc-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" style="fill:#8b9fbd;stroke:none"/></marker>';svg.append(defs);const edges=[];workers.forEach(n=>edges.push(['Navigator',n],[n,'review']));for(const p of messages()){const a=role(p.from),b=role(p.to);if(a!==b&&positions[a]&&positions[b]&&!edges.some(e=>e[0]===a&&e[1]===b))edges.push([a,b]);}for(const [a,b]of edges){const A=positions[a],B=positions[b];if(!A||!B)continue;const path=document.createElementNS('http://www.w3.org/2000/svg','path'),dx=B.x>A.x?76:-76;path.setAttribute('d',`M ${A.x+dx} ${A.y} C ${(A.x+B.x)/2} ${A.y}, ${(A.x+B.x)/2} ${B.y}, ${B.x-dx} ${B.y}`);path.setAttribute('class',a===selected||b===selected?'active':'');path.setAttribute('marker-end','url(#tc-arrow)');svg.append(path);}const chips=root.querySelector('.tc-edge-messages');chips.replaceChildren();const groups=new Map();for(const p of messages()){const from=role(p.from),to=role(p.to);if(!positions[from]||!positions[to]||from===to)continue;const key=from+'→'+to;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p);}let edgeIndex=0;for(const rows of groups.values()){const p=rows.at(-1),A=positions[role(p.from)],B=positions[role(p.to)];const b=make('button',rows.length+' 条消息 · '+(p.summary||'查看往返内容'),'tc-message-chip');b.type='button';b.title=role(p.from)+' → '+role(p.to)+'：'+p.summary;b.style.left=Math.max(8,(A.x+B.x)/2-70)+'px';b.style.top=((A.y+B.y)/2-26+(edgeIndex++%2)*26)+'px';b.onclick=()=>{selected=role(p.to);selectedJob=null;scope='node';tab='messages';renderDetails();const target=[...root.querySelectorAll('[data-message-id]')].find(x=>x.dataset.messageId===p.id);target?.scrollIntoView({block:'nearest',behavior:'smooth'});};chips.append(b);}}

  function renderActivity(){const box=root.querySelector('.tc-activity>div');box.replaceChildren();const rows=(task.operations?.activity||[]).slice(-8).reverse();if(rows.length){for(const e of rows){const b=make('button',null,'tc-update');b.type='button';b.append(make('time',time(e.at)),make('strong',e.node||'Navigator'),make('p',e.summary||e.title));b.onclick=()=>select(e.node||'Navigator','work');box.append(b);}return;}for(const e of events().slice(-8).reverse()){const b=make('button',null,'tc-update');b.type='button';b.append(make('time',time(e.at)),make('strong',role(e.role||e.from)||'Navigator'),make('p',e.message?.summary||title(e)));b.onclick=()=>select(role(e.role||e.from)||'Navigator','work');box.append(b);}}
  function renderDetails(){if(!task)return;root.querySelector('.tc-work-heading h2').textContent=selected+' / '+(stages[nodeEvents(selected).at(-1)?.stage]||'节点工作台');root.querySelector('.tc-work-heading>span').textContent=state(selected).status;tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));const jobs=root.querySelector('.tc-jobs'),detail=root.querySelector('.tc-detail'),scroll=detail.scrollTop;const open=new Set([...detail.querySelectorAll('details[open]')].map(d=>d.dataset.key).filter(Boolean));jobs.replaceChildren();detail.replaceChildren();const s=state(selected);jobs.append(make('h3','当前工作'),make('p',s.text),make('small',s.at?'最近事件 '+time(s.at):'等待执行记录'));const es=nodeEvents(selected).filter(e=>e.round===task.round),starts=es.filter(e=>/stage_started|branch_progress|tool_started/.test(e.kind));jobs.append(make('h3','执行步骤'));if(!starts.length)jobs.append(make('p','尚无已记录的执行步骤','tc-muted'));for(const e of starts.slice(-12)){const b=make('button',title(e),'tc-job');b.type='button';b.append(make('small',time(e.at)));b.onclick=()=>{tab='logs';renderDetails();};jobs.append(b);}jobs.append(make('small','进度依据执行回执，不估算百分比。','tc-muted'));
    const device=lens(selected);if(device){jobs.replaceChildren(make('h3','应用分析器 · '+device.os),make('p',device.application),make('p',`${device.online?'在线':'离线'} · 已返回 ${device.completedSteps}/${device.totalSteps} 项采集证据`));detail.append(make('h3','现场采集与云端交互'),make('p','AppLens 提供现场证据，不是协作 Driver。'));payload(detail,{summary:device.summary,evidence:device.evidence});return;}
    if(tab==='messages'){const toolbar=make('div',null,'tc-message-toolbar');for(const [v,label]of [['node','当前节点'],['all','整个团队']]){const b=make('button',label);b.type='button';b.setAttribute('aria-pressed',String(scope===v));b.onclick=()=>{scope=v;renderDetails();};toolbar.append(b);}detail.append(toolbar);const rows=messages().filter(p=>scope==='all'||role(p.from)===selected||role(p.to)===selected);if(!rows.length)detail.append(make('p','该节点尚无已记录的交接消息。','tc-empty'));for(const p of rows){const a=make('article',null,'tc-message');a.dataset.messageId=p.id;const h=make('div',null,'tc-message-head');h.append(make('time',time(p.at)),make('strong',role(p.from)+' → '+role(p.to)),make('span',p.status,'tc-receipt'));a.append(h);if(p.content!=null)payload(a,p.content);else{a.append(make('p',p.summary),make('small','历史记录仅保存摘要，没有完整正文。','tc-muted'));}if(p.correlationId)a.append(make('small','回复消息 '+p.correlationId));const d=make('details');d.dataset.key=p.id;d.open=open.has(p.id);d.append(make('summary','交接与处理记录 · 第 '+p.round+' 轮'));for(const e of p.receipts)d.append(make('p',time(e.at)+' · '+title(e)));a.append(d);detail.append(a);}}
    else if(tab==='logs'){for(const e of es){const a=make('article',null,'tc-log');a.append(make('small',time(e.at)),make('h3',title(e)));if(e.receipt)payload(a,e.receipt);else if(e.arguments)payload(a,{arguments:e.arguments});else if(e.evidence)payload(a,e.evidence);detail.append(a);}for(const m of task.messages||[]){if(role(m.role)!==selected)continue;const a=make('article',null,'tc-log');a.append(make('h3','第 '+m.round+' 轮 · '+(stages[m.stage]||'产出')));payload(a,m.answer||m.text);detail.append(a);}if(!detail.childElementCount)detail.append(make('p','尚无日志或产物。','tc-empty'));}
    else{detail.append(make('h3','实际执行记录'));for(const e of es.slice(-20)){const a=make('article',null,'tc-log');a.append(make('small',time(e.at)),make('p',title(e)));if(e.kind==='tool_started')payload(a,{arguments:e.arguments});if(e.receipt)payload(a,e.receipt);detail.append(a);}if(!es.length)detail.append(make('p','尚无执行记录。','tc-empty'));}
    const runningTool=[...es].reverse().find(e=>e.kind==='tool_started');
    if(runningTool){jobs.append(make('h3','最近执行的工具'),make('pre',JSON.stringify(runningTool.arguments||{},null,2)));}
    detail.scrollTop=follow?detail.scrollHeight:scroll;root.querySelector('.tc-new').textContent=unread?`新增 ${unread} 条事件`:'所有内容来自任务记录';}
  function update(t){const changed=task?.id!==t.id;if(changed){selectedJob=null;selected='Navigator';signature='';unread=0;}const oldCount=task?.events?.length||0;task=t;root.hidden=false;document.querySelector('.team-nodes').hidden=true;root.querySelector('.tc-heading h1').textContent=t.title;const acceptance=t.operations?.acceptance;root.querySelector('.tc-heading p').textContent=acceptance?.total?`已通过 ${acceptance.passed} / ${acceptance.total} 项验收 · 第 ${t.round} 轮 · ${nodes().length} 个协作角色`:`第 ${t.round} 轮 · ${nodes().length} 个协作角色 · 尚无验收结论`;root.querySelector('.tc-task-status').textContent=labels[t.status]||t.status;const next=JSON.stringify(t);if(next===signature)return;signature=next;if(!follow&&!changed)unread+=Math.max(0,events().length-oldCount);renderGraph();renderActivity();if(changed||follow)renderDetails();else root.querySelector('.tc-new').textContent=unread?`新增 ${unread} 条事件 · 开启跟随最新可更新`:'所有内容来自任务记录';document.querySelector('.hero').classList.add('hidden');}
  function renderJob(){
    const list=(task.operations?.jobs||[]).filter(j=>j.node===selected);
    if(!list.length)return;
    const job=list.find(j=>j.id===selectedJob)||list.at(-1);selectedJob=job.id;
    const box=root.querySelector('.tc-jobs');box.replaceChildren();
    root.querySelector('.tc-work-heading h2').textContent=selected+' / '+job.label+' · '+job.title;
    const statusLabels={queued:'等待执行',pending:'未开始',running:'执行中',completed:'已完成',failed:'失败',interrupted:'已中断'};
    const picker=make('select');picker.setAttribute('aria-label','选择节点任务');
    for(const j of list){const option=make('option',j.label+' · '+j.title+' · 第 '+j.round+' 轮');option.value=j.id;option.selected=j.id===job.id;picker.append(option);}
    picker.onchange=()=>{selectedJob=picker.value;renderDetails();};box.append(picker);
    box.append(make('h3',job.label+' · '+(statusLabels[job.status]||job.status)));
    const progress=make('progress');progress.max=job.progress.total;progress.value=job.progress.completed;progress.setAttribute('aria-label','已完成执行步骤');box.append(progress,make('small',job.progress.completed+' / '+job.progress.total+' 步'));
    for(const step of job.steps||[]){const line=make('div',null,'tc-operation-step');line.dataset.status=step.status;line.append(make('span',step.status==='completed'?'✓':step.status==='running'?'◉':'○'),make('strong',step.title),make('small',statusLabels[step.status]||step.status));box.append(line);}
    if(job.waitingReason)box.append(make('p','等待：'+job.waitingReason,'tc-waiting'));
    const tool=job.tools?.at(-1);if(tool){box.append(make('h3','当前 / 最近执行'),make('p',tool.name));box.append(make('pre',tool.arguments?.command||JSON.stringify(tool.arguments||{},null,2)));}
    if(tab==='work'){const detail=root.querySelector('.tc-detail');detail.replaceChildren();detail.append(make('h3','任务目标'),make('p',job.objective||job.title));for(const entry of job.logs||[]){const a=make('article',null,'tc-log');a.append(make('small',time(entry.at)),make('p',entry.text));if(entry.receipt)payload(a,entry.receipt);detail.append(a);}if(job.output){detail.append(make('h3','阶段结果'));payload(detail,job.output);}}
  }
  const renderEventDetails=renderDetails;renderDetails=()=>{renderEventDetails();renderJob();};
  const oldRender=render;render=t=>{oldRender(t);update(t);};
  const create=$('new-task').onclick;$('new-task').onclick=()=>{create();root.hidden=true;task=null;document.querySelector('.team-nodes').hidden=false;document.querySelector('.hero').classList.remove('hidden');};
  window.addEventListener('agentpair:nodes',()=>{if(task)renderGraph();});
  new ResizeObserver(()=>{if(task)renderGraph();}).observe(root.querySelector('.tc-canvas'));
  if(current)api('/api/tasks/'+current).then(update).catch(()=>{});
})();
